[tool.ruff]
line-length = 120
target-version = "py313"
src = ["app"]
exclude = [
  "__old",
  "alembic",
  "**/node_modules",
  "**/__pycache__",
  "docker",
  ".venv",
  "*.venv",
  "app/tests",
  ".pytest_cache",
]

[tool.ruff.format]
quote-style = "double"
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",        # Ignore docstring style
  "PGH",      # Ignore pygrep-hooks (e.g. noqa w/o explanation)
  "T20",      # Allow print statements
  "ERA",      # Allow commented-out code
  "COM812",   # Formatter conflict (trailing commas)
  "UP007",    # Prevents rewriting Optional[...] to X | None
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"app/extensions/mssql_search/endpoints/search.py" = ["S608"]
"app/extensions/mssql_search/endpoints/valid_search.py" = ["S608"]
