[project]
requires-python = ">=3.13"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "E712", # true-false-comparison: Which is unreadable in sqlalchemy filters
]

[tool.pytest.ini_options]
norecursedirs = "*venv* *.venv* *.pytest_cache*"
testpaths = "app/tests"
