from .list_acknowledged_relations import ListAcknowledgedRelationsEndpointResolver
from .request_acknowledged_relation import RequestAcknowledgedRelationEndpointResolver
from .edit_acknowledged_relation import EditAcknowledgedRelationEndpointResolver
