from .create_template import CreatePublicationTemplateEndpointResolver
from .edit_template import EditPublicationTemplateEndpointResolver
from .list_templates import ListPublicationTemplatesEndpointResolver
