from .crud_ambitie import CRUDAmbitie
from .crud_belang import CRUDBelang
from .crud_beleidskeuze import CRUDBeleidskeuze
from .crud_beleidsmodule import CRUDBeleidsmodule
from .crud_beleidsdoel import CRUDBeleidsdoel
from .crud_beleidsprestatie import CRUDBeleidsprestatie
from .crud_beleidsrelatie import CRUDBeleidsrelatie
from .crud_beleidsregel import CRUDBeleidsregel
from .crud_maatregel import CRUDMaatregel
from .crud_thema import CRUDThema
from .crud_verordening import CRUDVerordening
from .crud_verordeningstructuur import CRUDVerordeningstructuur
from .crud_gebruiker import CRUDGebruiker
from .crud_werkingsgebied import CRUDWerkingsgebied
