from os import wait
from .crud_ambitie import ambitie
from .crud_belang import belang
from .crud_beleidskeuze import beleidskeuze
from .crud_beleidsmodule import beleidsmodule
from .crud_beleidsdoel import beleidsdoel
from .crud_beleidsprestatie import beleidsprestatie
from .crud_beleidsrelatie import beleidsrelatie
from .crud_beleidsregel import beleidsregel
from .crud_gebeidsprogramma import gebiedsprogramma
from .crud_maatregel import maatregel
from .crud_thema import thema
from .crud_verordening import verordening
from .crud_verordeningstructuur import verordeningstructuur
from .crud_gebruiker import gebruiker
from .crud_werkingsgebied import werkingsgebied
