"""dev_werkingsgebieden

Revision ID: 00c1d7bd6337
Revises: 8bdf199b3b73
Create Date: 2024-01-31 11:05:12.803343

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import settings  ## noqa
from app.extensions.source_werkingsgebieden.geometry import Geometry  ## noqa

# revision identifiers, used by Alembic.
revision = "00c1d7bd6337"
down_revision = "8bdf199b3b73"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Onderverdeling",
        sa.Column("UUID", sa.Uuid(), nullable=False),
        sa.Column("ID", sa.Integer(), nullable=False),
        sa.Column("Onderverdeling", sa.String(), nullable=False),
        sa.Column("SHAPE", Geometry(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("Werkingsgebied", sa.Unicode(length=265), nullable=False),
        sa.Column("UUID_Werkingsgebied", sa.Uuid(), nullable=False),
        sa.Column("Created_Date", sa.DateTime(), nullable=False),
        sa.Column("Modified_Date", sa.DateTime(), nullable=False),
        sa.Column("Begin_Geldigheid", sa.DateTime(), nullable=False),
        sa.Column("Eind_Geldigheid", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("UUID"),
    )
    op.add_column(
        "Werkingsgebieden",
        sa.Column("SHAPE", Geometry(), nullable=True),
    )
    op.add_column("Werkingsgebieden", sa.Column("symbol", sa.Unicode(length=265), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Werkingsgebieden", "symbol")
    op.drop_column("Werkingsgebieden", "SHAPE")
    op.drop_table("Onderverdeling")
    # ### end Alembic commands ###
