"""empty message

Revision ID: 0782a392777e
Revises: 39b0dc192d1f
Create Date: 2023-05-08 12:03:04.829615

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0782a392777e'
down_revision = '39b0dc192d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulations')
    op.drop_table('object_regulations')
    op.alter_column('acknowledged_relations', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('acknowledged_relations', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('module_object_context', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('module_object_context', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('module_objects', sa.Column('Accomplish', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Effect', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Role', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Image', sa.String(), nullable=True))
    op.alter_column('modules', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('modules', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('objects', sa.Column('Accomplish', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Effect', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Role', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Image')
    op.drop_column('objects', 'Role')
    op.drop_column('objects', 'Effect')
    op.drop_column('objects', 'Accomplish')
    op.alter_column('modules', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('modules', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('module_objects', 'Image')
    op.drop_column('module_objects', 'Role')
    op.drop_column('module_objects', 'Effect')
    op.drop_column('module_objects', 'Accomplish')
    op.alter_column('module_object_context', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('module_object_context', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('acknowledged_relations', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('acknowledged_relations', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_table('object_regulations',
    sa.Column('Object_Code', sa.VARCHAR(length=35, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Regulation_UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Object_Code'], ['object_statics.Code'], name='FK__object_re__Objec__6383C8BA'),
    sa.ForeignKeyConstraint(['Regulation_UUID'], ['regulations.UUID'], name='FK__object_re__Regul__6477ECF3'),
    sa.PrimaryKeyConstraint('Object_Code', 'Regulation_UUID', name='PK__object_r__C4E84EE42748084C')
    )
    op.create_table('regulations',
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('Created_Date', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('Created_By_UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('Modified_Date', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('Modified_By_UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('Title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Type', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], name='FK__regulatio__Creat__5FB337D6'),
    sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], name='FK__regulatio__Modif__60A75C0F'),
    sa.PrimaryKeyConstraint('UUID', name='PK__regulati__65A475E74861CFBB')
    )
    # ### end Alembic commands ###
