"""empty message

Revision ID: 0782a392777e
Revises: 39b0dc192d1f
Create Date: 2023-05-08 12:03:04.829615

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0782a392777e'
down_revision = '39b0dc192d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acknowledged_relations', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('acknowledged_relations', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('module_object_context', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('module_object_context', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('module_objects', sa.Column('Accomplish', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Effect', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Role', sa.String(), nullable=True))
    op.add_column('module_objects', sa.Column('Image', sa.String(), nullable=True))
    op.alter_column('modules', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('modules', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('objects', sa.Column('Accomplish', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Effect', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Role', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('Image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Image')
    op.drop_column('objects', 'Role')
    op.drop_column('objects', 'Effect')
    op.drop_column('objects', 'Accomplish')
    op.alter_column('modules', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('modules', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('module_objects', 'Image')
    op.drop_column('module_objects', 'Role')
    op.drop_column('module_objects', 'Effect')
    op.drop_column('module_objects', 'Accomplish')
    op.alter_column('module_object_context', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('module_object_context', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('acknowledged_relations', 'Modified_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('acknowledged_relations', 'Created_Date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
