"""Create the possibility to have multiple roles for a user

Revision ID: 0832ffb0b2e9
Revises: c704f8f17f09
Create Date: 2026-08-19 11:03:39.455786

"""

from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import Settings  ## noqa


# revision identifiers, used by Alembic.
revision = "0832ffb0b2e9"
down_revision = "c704f8f17f09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("User_UUID", sa.Uuid(), nullable=False),
        sa.Column("Role", sa.Unicode(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["User_UUID"],
            ["Gebruikers.UUID"],
        ),
        sa.PrimaryKeyConstraint("User_UUID", "Role"),
    )

    # Query to change the existing roles to the new roles table. (Doubt if this is the place to do it or just once via the terminal)
    op.execute("""
            INSERT INTO user_roles (User_UUID, Role)
            SELECT UUID,
                CASE Rol
                    WHEN 'Beheerder' THEN 'Superuser'
                    WHEN 'Functioneel beheerder' THEN 'Regisseur Omgevingsbeleid'
                    WHEN 'Technisch beheerder' THEN 'Technisch Beheerder'
                    WHEN 'Tester' THEN 'Superuser'
                    WHEN 'Test runner' THEN 'Superuser'
                    ELSE Rol
                END
            FROM Gebruikers
            WHERE Rol IS NOT NULL
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    # ### end Alembic commands ###
