"""Input GEO Onderverdeling Added Symbol

Revision ID: 276828ec0bcc
Revises: 6df1c10e0bfd
Create Date: 2026-01-13 08:16:14.539337

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '276828ec0bcc'
down_revision = '6df1c10e0bfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Input_GEO_Onderverdeling', sa.Column('Symbol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Input_GEO_Onderverdeling', 'Symbol')
    # ### end Alembic commands ###
