"""empty message

Revision ID: 2dbf768b0401
Revises: 0782a392777e
Create Date: 2023-05-09 07:39:58.903584

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '2dbf768b0401'
down_revision = '0782a392777e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acknowledged_relations', sa.Column('Denied', sa.DateTime(), nullable=True))
    op.add_column('acknowledged_relations', sa.Column('Deleted_At', sa.DateTime(), nullable=True))
    op.alter_column('acknowledged_relations', 'From_Acknowledged',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('acknowledged_relations', 'To_Acknowledged',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('acknowledged_relations', 'To_Acknowledged_Date')
    op.drop_column('acknowledged_relations', 'From_Acknowledged_Date')
    op.drop_column('acknowledged_relations', 'From_Title')
    op.drop_column('acknowledged_relations', 'To_Title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acknowledged_relations', sa.Column('From_Acknowledged_Date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.add_column('acknowledged_relations', sa.Column('To_Acknowledged_Date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.alter_column('acknowledged_relations', 'To_Acknowledged',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('acknowledged_relations', 'From_Acknowledged',
               existing_type=mssql.BIT(),
               nullable=False)
    op.drop_column('acknowledged_relations', 'Deleted_At')
    op.drop_column('acknowledged_relations', 'Denied')
    op.add_column('acknowledged_relations', sa.Column('To_Title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('acknowledged_relations', sa.Column('From_Title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
