"""Add object documents

Revision ID: 3261e6b8f1e5
Revises: 348162e768ec
Create Date: 2024-12-02 09:19:32.813497

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 


# revision identifiers, used by Alembic.
revision = '3261e6b8f1e5'
down_revision = '348162e768ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_files',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Lookup', sa.Unicode(length=10), nullable=False),
        sa.Column('Checksum', sa.String(length=64), nullable=False),
        sa.Column('Filename', sa.Unicode(length=255), nullable=False),
        sa.Column('Content_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Size', sa.Integer(), nullable=False),
        sa.Column('Binary', sa.LargeBinary(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_index(op.f('ix_storage_files_Lookup'), 'storage_files', ['Lookup'], unique=False)
    
    op.add_column('module_objects', sa.Column('Filename', sa.Unicode(), nullable=True))
    op.add_column('module_objects', sa.Column('Documents', sa.JSON(), nullable=True))
    op.add_column('module_objects', sa.Column('File_UUID', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_ModuleObjectsTable_File_UUID_to_storagefile_uuid', 'module_objects', 'storage_files', ['File_UUID'], ['UUID'])
    
    op.add_column('objects', sa.Column('Filename', sa.Unicode(), nullable=True))
    op.add_column('objects', sa.Column('Documents', sa.JSON(), nullable=True))
    op.add_column('objects', sa.Column('File_UUID', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_ObjectsTable_File_UUID_to_storagefile_uuid', 'objects', 'storage_files', ['File_UUID'], ['UUID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ObjectsTable_File_UUID_to_storagefile_uuid', 'objects', type_='foreignkey')
    op.drop_column('objects', 'File_UUID')
    op.drop_column('objects', 'Documents')
    op.drop_column('objects', 'Filename')
    
    op.drop_constraint('fk_ModuleObjectsTable_File_UUID_to_storagefile_uuid', 'module_objects', type_='foreignkey')
    op.drop_column('module_objects', 'File_UUID')
    op.drop_column('module_objects', 'Documents')
    op.drop_column('module_objects', 'Filename')
    
    op.drop_index(op.f('ix_storage_files_Lookup'), table_name='storage_files')
    op.drop_table('storage_files')
    # ### end Alembic commands ###
