""" Publication state V2

Revision ID: 348162e768ec
Revises: 8455fd1c7d2d
Create Date: 2024-08-06 12:37:27.446619

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 


# revision identifiers, used by Alembic.
revision = '348162e768ec'
down_revision = '8455fd1c7d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_area_of_jurisdictions', sa.Column('Title', sa.Unicode(), server_default='', nullable=False))
    op.alter_column('publication_acts', 'Procedure_Type', existing_type=sa.NVARCHAR(length=50), nullable=True)
    op.add_column('publication_environments', sa.Column('Code', sa.Unicode(length=32), nullable=True))

    # Update column data where possible
    op.execute(
        "UPDATE publication_area_of_jurisdictions SET Administrative_Borders_ID = 'PV28' WHERE Administrative_Borders_ID = '002000000000000000099928';"
    )
    op.execute(
        "UPDATE publication_area_of_jurisdictions SET Title = 'Provincie Zuid-Holland' WHERE Title = '';"
    )
    op.execute(
        """
        UPDATE publication_environments
        SET Code = CASE
            WHEN Title = 'PlanoView' THEN 'PLAN'
            WHEN Title = 'Pre-Prod' THEN 'PRE'
            WHEN Title = 'Prod' THEN 'PROD'
        END
        WHERE Code IS NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_area_of_jurisdictions', 'Title')
    op.drop_column('publication_environments', 'Code')
    op.alter_column('publication_acts', 'Procedure_Type', existing_type=sa.NVARCHAR(length=50), nullable=False)
    # ### end Alembic commands ###
