"""Added publication mutation strategy

Revision ID: 39886023a73b
Revises: 4c4bfe3fe443
Create Date: 2026-07-14 10:01:59.775369

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '39886023a73b'
down_revision = '4c4bfe3fe443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_versions', sa.Column('Mutation_Strategy', sa.Unicode(length=64), server_default='renvooi', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_versions', 'Mutation_Strategy')
    # ### end Alembic commands ###
