"""Adding many to many relation for werkingsgebieden and onderverdelingen

Revision ID: 39a51a652bd7
Revises: b5dae5845174
Create Date: 2025-07-16 14:34:52.323801

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa
from app.core.db.geometry import Geometry  ## noqa

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '39a51a652bd7'
down_revision = 'b5dae5845174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Input_GEO_Werkingsgebieden_Onderverdelingen',
        sa.Column('Werkingsgebied_UUID', sa.Uuid(), nullable=False),
        sa.Column('Onderverdeling_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Onderverdeling_UUID'], ['Input_GEO_Onderverdeling.UUID'], ),
        sa.ForeignKeyConstraint(['Werkingsgebied_UUID'], ['Input_GEO_Werkingsgebieden.UUID'], ),
        sa.PrimaryKeyConstraint('Werkingsgebied_UUID', 'Onderverdeling_UUID')
    )

    op.drop_constraint(op.f('FK__Input_GEO__Werki__756D6ECB'), 'Input_GEO_Onderverdeling', type_='foreignkey')

    op.drop_column('Input_GEO_Onderverdeling', 'Werkingsgebied_UUID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Input_GEO_Onderverdeling', sa.Column('Werkingsgebied_UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__Input_GEO__Werki__756D6ECB'), 'Input_GEO_Onderverdeling', 'Input_GEO_Werkingsgebieden', ['Werkingsgebied_UUID'], ['UUID'])
    op.drop_table('Input_GEO_Werkingsgebieden_Onderverdelingen')
    # ### end Alembic commands ###
