"""empty message

Revision ID: 39b0dc192d1f
Revises: cad90da70a44
Create Date: 2023-04-24 15:14:54.935983

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '39b0dc192d1f'
down_revision = 'cad90da70a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Title', sa.String(), nullable=False),
        sa.Column('Type', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('object_regulations',
        sa.Column('Object_Code', sa.String(length=35), nullable=False),
        sa.Column('Regulation_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Object_Code'], ['object_statics.Code'], ),
        sa.ForeignKeyConstraint(['Regulation_UUID'], ['regulations.UUID'], ),
        sa.PrimaryKeyConstraint('Object_Code', 'Regulation_UUID')
    )
    op.drop_table('object_werkingsgebieden')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_werkingsgebieden',
        sa.Column('Object_Code', sa.VARCHAR(length=35, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
        sa.Column('Werkingsgebied_UUID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
        sa.Column('Description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['Object_Code'], ['object_statics.Code'], name='FK__object_we__Objec__4AB81AF0'),
        sa.ForeignKeyConstraint(['Werkingsgebied_UUID'], ['Werkingsgebieden.UUID'], name='FK__object_we__Werki__4BAC3F29'),
        sa.PrimaryKeyConstraint('Object_Code', 'Werkingsgebied_UUID', name='PK__object_w__F4E168390E75161F')
    )
    op.drop_table('object_regulations')
    op.drop_table('regulations')
    # ### end Alembic commands ###
