"""empty message

Revision ID: 39b0dc192d1f
Revises: cad90da70a44
Create Date: 2023-04-24 15:14:54.935983

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '39b0dc192d1f'
down_revision = 'cad90da70a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
