"""empty message

Revision ID: 43f8adfab60c
Revises: 7cb2d113ad32
Create Date: 2024-03-29 15:46:01.919301

"""
from alembic import op
import sqlalchemy as sa
from app.extensions.source_werkingsgebieden import geometry  ## noqa
from app.extensions.source_werkingsgebieden.geometry import Geometry  ## noqa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = '43f8adfab60c'
down_revision = '7cb2d113ad32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_environment_states',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Adjust_On_UUID', sa.Uuid(), nullable=True),
        sa.Column('Is_Activated', sa.Boolean(), nullable=False),
        sa.Column('Activated_Datetime', sa.DateTime(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('State', sa.JSON(), nullable=True),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Adjust_On_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_environments',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Description', sa.Unicode(), nullable=False),
        sa.Column('Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Authority_ID', sa.Unicode(length=20), nullable=False),
        sa.Column('Submitter_ID', sa.Unicode(length=20), nullable=False),
        sa.Column('Governing_Body_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Frbr_Country', sa.Unicode(length=2), nullable=False),
        sa.Column('Frbr_Language', sa.Unicode(length=3), nullable=False),
        sa.Column('Is_Active', sa.Boolean(), nullable=False),
        sa.Column('Has_State', sa.Boolean(), nullable=False),
        sa.Column('Can_Validate', sa.Boolean(), nullable=False),
        sa.Column('Can_Publicate', sa.Boolean(), nullable=False),
        sa.Column('Is_Locked', sa.Boolean(), nullable=False),
        sa.Column('Active_State_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Active_State_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_foreign_key('fk_pub_state_to_env',
        source_table='publication_environment_states',
        referent_table='publication_environments',
        local_cols=['Environment_UUID'],
        remote_cols=['UUID'],
    )
    op.create_table('publication_area_of_jurisdictions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Administrative_Borders_ID', sa.Unicode(length=255), nullable=False),
        sa.Column('Administrative_Borders_Domain', sa.Unicode(length=255), nullable=False),
        sa.Column('Administrative_Borders_Date', sa.Date(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_bills',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(), nullable=False),
        sa.Column('Work_Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Country', sa.Unicode(length=2), nullable=False),
        sa.Column('Work_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Environment_UUID', 'Work_Other', name='uix_pub_bil_env_other')
    )
    op.create_table('publication_docs',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(), nullable=False),
        sa.Column('Work_Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Country', sa.Unicode(length=2), nullable=False),
        sa.Column('Work_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Environment_UUID', 'Work_Other', name='uix_pub_doc_env_other')
    )
    op.create_table('publication_package_zips',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Filename', sa.Unicode(), nullable=False),
        sa.Column('Binary', sa.LargeBinary(), nullable=False),
        sa.Column('Checksum', sa.String(length=64), nullable=False),
        sa.Column('Latest_Download_Date', sa.DateTime(), nullable=True),
        sa.Column('Latest_Download_By_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Latest_Download_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_purposes',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Purpose_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Effective_Date', sa.Date(), nullable=True),
        sa.Column('Work_Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Environment_UUID', 'Work_Other', name='uix_pub_pur_env_other')
    )
    op.create_table('publication_templates',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Description', sa.Unicode(), nullable=False),
        sa.Column('Is_Active', sa.Boolean(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(), nullable=False),
        sa.Column('Object_Types', sa.JSON(), nullable=False),
        sa.Column('Text_Template', sa.Unicode(), nullable=False),
        sa.Column('Object_Templates', sa.JSON(), nullable=False),
        sa.Column('Field_Map', sa.JSON(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_acts',
        sa.Column('ID', sa.Integer(), nullable=False),
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Procedure_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Is_Active', sa.Boolean(), nullable=False),
        sa.Column('Metadata', sa.JSON(), nullable=True),
        sa.Column('Metadata_Is_Locked', sa.Boolean(), nullable=False),
        sa.Column('Work_Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Country', sa.Unicode(length=2), nullable=False),
        sa.Column('Work_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Withdrawal_Purpose_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Withdrawal_Purpose_UUID'], ['publication_purposes.UUID'], ),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Environment_UUID', 'Work_Other', name='uix_pub_act_env_other'),
        sa.UniqueConstraint('UUID')
    )
    op.create_table('publication_bill_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Bill_UUID', sa.Uuid(), nullable=False),
        sa.Column('Expression_Language', sa.Unicode(length=3), nullable=False),
        sa.Column('Expression_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Expression_Version', sa.Integer(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Bill_UUID'], ['publication_bills.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Bill_UUID', 'Expression_Version', name='uix_bill_version')
    )
    op.create_table('publication_doc_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Doc_UUID', sa.Uuid(), nullable=False),
        sa.Column('Expression_Language', sa.Unicode(length=3), nullable=False),
        sa.Column('Expression_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Expression_Version', sa.Integer(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Doc_UUID'], ['publication_docs.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Doc_UUID', 'Expression_Version', name='uix_doc_version')
    )
    op.create_table('publication_act_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Act_UUID', sa.Uuid(), nullable=False),
        sa.Column('Consolidation_Purpose_UUID', sa.Uuid(), nullable=False),
        sa.Column('Expression_Language', sa.Unicode(length=3), nullable=False),
        sa.Column('Expression_Date', sa.Unicode(length=32), nullable=False),
        sa.Column('Expression_Version', sa.Integer(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_UUID'], ['publication_acts.UUID'], ),
        sa.ForeignKeyConstraint(['Consolidation_Purpose_UUID'], ['publication_purposes.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Act_UUID', 'Expression_Version', name='uix_act_version')
    )
    op.create_table('publications',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Module_ID', sa.Integer(), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Procedure_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Template_UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Act_UUID', sa.Uuid(), nullable=False),
        sa.Column('Is_Locked', sa.Boolean(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_UUID'], ['publication_acts.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Module_ID'], ['modules.Module_ID'], ),
        sa.ForeignKeyConstraint(['Template_UUID'], ['publication_templates.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_UUID', sa.Uuid(), nullable=False),
        sa.Column('Module_Status_ID', sa.Integer(), nullable=False),
        sa.Column('Effective_Date', sa.Date(), nullable=True),
        sa.Column('Announcement_Date', sa.Date(), nullable=True),
        sa.Column('Bill_Metadata', sa.JSON(), nullable=True),
        sa.Column('Bill_Compact', sa.JSON(), nullable=True),
        sa.Column('Procedural', sa.JSON(), nullable=True),
        sa.Column('Is_Locked', sa.Boolean(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Module_Status_ID'], ['module_status_history.ID'], ),
        sa.ForeignKeyConstraint(['Publication_UUID'], ['publications.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_act_packages',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_Version_UUID', sa.Uuid(), nullable=False),
        sa.Column('Bill_Version_UUID', sa.Uuid(), nullable=True),
        sa.Column('Act_Version_UUID', sa.Uuid(), nullable=True),
        sa.Column('Zip_UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Report_Status', sa.Unicode(length=64), nullable=False),
        sa.Column('Delivery_ID', sa.String(length=80), nullable=False),
        sa.Column('Used_Environment_State_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Environment_State_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_Version_UUID'], ['publication_act_versions.UUID'], ),
        sa.ForeignKeyConstraint(['Bill_Version_UUID'], ['publication_bill_versions.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Created_Environment_State_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Publication_Version_UUID'], ['publication_versions.UUID'], ),
        sa.ForeignKeyConstraint(['Used_Environment_State_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Zip_UUID'], ['publication_package_zips.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_act_package_reports',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Act_Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Report_Status', sa.Unicode(), nullable=False),
        sa.Column('Filename', sa.Unicode(), nullable=False),
        sa.Column('Source_Document', sa.UnicodeText(), nullable=False),
        sa.Column('Main_Outcome', sa.Unicode(), nullable=False),
        sa.Column('Sub_Delivery_ID', sa.String(length=80), nullable=False),
        sa.Column('Sub_Progress', sa.Unicode(length=100), nullable=False),
        sa.Column('Sub_Outcome', sa.Unicode(length=100), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_Package_UUID'], ['publication_act_packages.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_announcements',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Act_Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_UUID', sa.Uuid(), nullable=False),
        sa.Column('Announcement_Date', sa.Date(), nullable=True),
        sa.Column('Metadata', sa.JSON(), nullable=True),
        sa.Column('Procedural', sa.JSON(), nullable=True),
        sa.Column('Content', sa.JSON(), nullable=True),
        sa.Column('Is_Locked', sa.Boolean(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_Package_UUID'], ['publication_act_packages.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Publication_UUID'], ['publications.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_announcement_packages',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Announcement_UUID', sa.Uuid(), nullable=False),
        sa.Column('Doc_Version_UUID', sa.Uuid(), nullable=True),
        sa.Column('Zip_UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Report_Status', sa.Unicode(length=64), nullable=False),
        sa.Column('Delivery_ID', sa.String(length=80), nullable=False),
        sa.Column('Used_Environment_State_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Environment_State_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Announcement_UUID'], ['publication_announcements.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Created_Environment_State_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Doc_Version_UUID'], ['publication_doc_versions.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Used_Environment_State_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Zip_UUID'], ['publication_package_zips.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_announcement_package_reports',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Announcement_Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Report_Status', sa.Unicode(), nullable=False),
        sa.Column('Filename', sa.Unicode(), nullable=False),
        sa.Column('Source_Document', sa.UnicodeText(), nullable=False),
        sa.Column('Main_Outcome', sa.Unicode(), nullable=False),
        sa.Column('Sub_Delivery_ID', sa.String(length=80), nullable=False),
        sa.Column('Sub_Progress', sa.Unicode(length=100), nullable=False),
        sa.Column('Sub_Outcome', sa.Unicode(length=100), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Announcement_Package_UUID'], ['publication_announcement_packages.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_announcement_package_reports')
    op.drop_table('publication_announcement_packages')
    op.drop_table('publication_announcements')
    op.drop_table('publication_act_package_reports')
    op.drop_table('publication_act_packages')
    op.drop_table('publication_versions')
    op.drop_table('publications')
    op.drop_table('publication_act_versions')
    op.drop_table('publication_doc_versions')
    op.drop_table('publication_bill_versions')
    op.drop_table('publication_acts')
    op.drop_table('publication_templates')
    op.drop_table('publication_purposes')
    op.drop_table('publication_package_zips')
    op.drop_table('publication_docs')
    op.drop_table('publication_bills')
    op.drop_table('publication_area_of_jurisdictions')
    op.drop_table('publication_environments')
    op.drop_table('publication_environment_states')
    # ### end Alembic commands ###
