"""empty message

Revision ID: 4da727d741b0
Revises: eb6126c067be
Create Date: 2023-05-16 12:21:46.742990

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = '4da727d741b0'
down_revision = 'eb6126c067be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'Start_Validity')
    op.drop_column('modules', 'End_Validity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('End_Validity', sa.DATETIME(), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('Start_Validity', sa.DATETIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
