"""Make Gebruikers.Rol nullable

Revision ID: 4ea414f3eacb
Revises: 80143fa75c0b
Create Date: 2026-09-02 11:50:23.562843

"""

from alembic import op
from app.core.db import table_metadata  ## noqa
from app.core.settings import Settings

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa

settings = Settings()


# revision identifiers, used by Alembic.
revision = "4ea414f3eacb"
down_revision = "80143fa75c0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Gebruikers", "Rol", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Gebruikers", "Rol", nullable=False)
    # ### end Alembic commands ###
