"""Added object_related_files

Revision ID: 53b64fe95852
Revises: 826c32155e0a
Create Date: 2026-06-23 08:38:05.709719

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '53b64fe95852'
down_revision = '826c32155e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_related_files',
    sa.Column('UUID', sa.Uuid(), nullable=False),
    sa.Column('Object_Code', sa.Unicode(length=35), nullable=False),
    sa.Column('File_UUID', sa.Uuid(), nullable=False),
    sa.Column('Title', sa.Unicode(length=255), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['File_UUID'], ['storage_files.UUID'], ),
    sa.ForeignKeyConstraint(['Object_Code'], ['object_statics.Code'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_index(op.f('ix_object_related_files_Object_Code'), 'object_related_files', ['Object_Code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_related_files_Object_Code'), table_name='object_related_files')
    op.drop_table('object_related_files')
    # ### end Alembic commands ###
