"""Input GEO Onderverdeling Added Description

Revision ID: 5f6dde59d68e
Revises: ffce58fd473e
Create Date: 2026-01-22 09:58:53.086775

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '5f6dde59d68e'
down_revision = 'ffce58fd473e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Input_GEO_Onderverdeling', sa.Column('Description', sa.String(), server_default='', nullable=False))
    op.add_column('Input_GEO_Werkingsgebieden', sa.Column('Description', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Input_GEO_Werkingsgebieden', 'Description')
    op.drop_column('Input_GEO_Onderverdeling', 'Description')
    # ### end Alembic commands ###
