"""Hierarchy Code added

Revision ID: 626adccffe91
Revises: a26a0e7d8262
Create Date: 2023-11-29 12:40:17.572798

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 


# revision identifiers, used by Alembic.
revision = '626adccffe91'
down_revision = 'a26a0e7d8262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_objects', sa.Column('Hierarchy_Code', sa.Unicode(), nullable=True))
    op.add_column('objects', sa.Column('Hierarchy_Code', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Hierarchy_Code')
    op.drop_column('module_objects', 'Hierarchy_Code')
    # ### end Alembic commands ###
