"""Implementation for Gebiedsaanwijzingen

Revision ID: 6df1c10e0bfd
Revises: b61f0705fca0
Create Date: 2025-12-18 09:24:28.837364

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '6df1c10e0bfd'
down_revision = 'b61f0705fca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_templates', sa.Column('Object_Field_Map', sa.JSON(), nullable=True))
    op.alter_column('publication_templates', 'Field_Map',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication_templates', 'Field_Map',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('publication_templates', 'Object_Field_Map')
