"""Adding GML to areas

Revision ID: 7cb2d113ad32
Revises: 00c1d7bd6337
Create Date: 2024-03-09 15:16:33.012620

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = '7cb2d113ad32'
down_revision = '00c1d7bd6337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('Gml', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'Gml')
    # ### end Alembic commands ###
