"""remove title from publications

Revision ID: 826c32155e0a
Revises: a4c647a3757e
Create Date: 2026-05-08 09:58:45.761276

"""

from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import Settings  ## noqa

settings = Settings()


# revision identifiers, used by Alembic.
revision = "826c32155e0a"
down_revision = "a4c647a3757e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "Title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publications",
        sa.Column("Title", sa.Unicode(), nullable=True),
    )
    # ### end Alembic commands ###
