"""updated OW objects relation to packages

Revision ID: 8847a66d97fa
Revises: f9a7fdcff4d7
Create Date: 2024-02-16 18:30:15.107928

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import settings  ## noqa

from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "8847a66d97fa"
down_revision = "f9a7fdcff4d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_package_ow_association",
        sa.Column("Package_UUID", sa.Uuid(), nullable=False),
        sa.Column("OW_ID_HASH", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["OW_ID_HASH"],
            ["publication_ow_objects.OW_ID_HASH"],
        ),
        sa.ForeignKeyConstraint(
            ["Package_UUID"],
            ["publication_packages.UUID"],
        ),
        sa.PrimaryKeyConstraint("Package_UUID", "OW_ID_HASH"),
    )
    op.drop_constraint("FK__publicati__Packa__18F6A22A", "publication_ow_objects", type_="foreignkey")
    op.drop_column("publication_ow_objects", "Package_UUID")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publication_ow_objects",
        sa.Column("Package_UUID", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "FK__publicati__Packa__18F6A22A", "publication_ow_objects", "publication_packages", ["Package_UUID"], ["UUID"]
    )
    op.drop_table("publication_package_ow_association")
    # ### end Alembic commands ###
