"""Added area system

Revision ID: 8bdf199b3b73
Revises: 58ad22156b8b
Create Date: 2024-01-26 09:10:36.840305

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 


# revision identifiers, used by Alembic.
revision = '8bdf199b3b73'
down_revision = '58ad22156b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Shape', sa.LargeBinary(), nullable=True),
        sa.Column('Source_UUID', sa.Uuid(), nullable=False),
        sa.Column('Source_ID', sa.Integer(), nullable=True),
        sa.Column('Source_Title', sa.String(), nullable=False),
        sa.Column('Source_Symbol', sa.String(), nullable=True),
        sa.Column('Source_Start_Validity', sa.DateTime(), nullable=False),
        sa.Column('Source_End_Validity', sa.DateTime(), nullable=False),
        sa.Column('Source_Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Source_Modified_Date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Source_UUID')
    )

    op.add_column('module_objects', sa.Column('Area_UUID', sa.Uuid(), nullable=True))
    op.add_column('module_objects', sa.Column('Werkingsgebied_Code', sa.Unicode(length=35), nullable=True))
    op.create_foreign_key(None, 'module_objects', 'object_statics', ['Werkingsgebied_Code'], ['Code'])
    op.create_foreign_key(None, 'module_objects', 'areas', ['Area_UUID'], ['UUID'])

    op.add_column('objects', sa.Column('Area_UUID', sa.Uuid(), nullable=True))
    op.add_column('objects', sa.Column('Werkingsgebied_Code', sa.Unicode(length=35), nullable=True))
    op.create_foreign_key(None, 'objects', 'areas', ['Area_UUID'], ['UUID'])
    op.create_foreign_key(None, 'objects', 'object_statics', ['Werkingsgebied_Code'], ['Code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'Werkingsgebied_Code')
    op.drop_column('objects', 'Area_UUID')
    
    op.drop_constraint(None, 'module_objects', type_='foreignkey')
    op.drop_constraint(None, 'module_objects', type_='foreignkey')
    op.drop_column('module_objects', 'Werkingsgebied_Code')
    op.drop_column('module_objects', 'Area_UUID')

    op.drop_table('areas')
    # ### end Alembic commands ###
