""" Adding publications

Revision ID: 8e81b7b754ea
Revises: 7cb2d113ad32
Create Date: 2024-03-09 20:40:50.011601

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = '8e81b7b754ea'
down_revision = '7cb2d113ad32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_acts',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Status', sa.String(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Work_Other')
    )
    op.create_table('publication_area_of_jurisdictions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Administrative_Borders_ID', sa.Unicode(length=255), nullable=False),
        sa.Column('Administrative_Borders_Domain', sa.Unicode(length=255), nullable=False),
        sa.Column('Administrative_Borders_Date', sa.Date(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_bills',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Work_Other', sa.Unicode(length=128), nullable=False),
        sa.Column('Status', sa.String(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Work_Other')
    )
    op.create_table('publication_environments',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Description', sa.Unicode(), nullable=False),
        sa.Column('Province_ID', sa.Unicode(length=32), nullable=False),
        sa.Column('Authority_ID', sa.Unicode(length=20), nullable=False),
        sa.Column('Submitter_ID', sa.Unicode(length=20), nullable=False),
        sa.Column('Governing_Body_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Frbr_Country', sa.Unicode(length=2), nullable=False),
        sa.Column('Frbr_Language', sa.Unicode(length=3), nullable=False),
        sa.Column('Is_Active', sa.Boolean(), nullable=False),
        sa.Column('Has_State', sa.Boolean(), nullable=False),
        sa.Column('Can_Validate', sa.Boolean(), nullable=False),
        sa.Column('Can_Publicate', sa.Boolean(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_templates',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Title', sa.Unicode(), nullable=False),
        sa.Column('Description', sa.Unicode(), nullable=False),
        sa.Column('Is_Active', sa.Boolean(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(), nullable=False),
        sa.Column('Object_Types', sa.JSON(), nullable=False),
        sa.Column('Text_Template', sa.Unicode(), nullable=False),
        sa.Column('Object_Templates', sa.JSON(), nullable=False),
        sa.Column('Field_Map', sa.JSON(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_act_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Act_UUID', sa.Uuid(), nullable=False),
        sa.Column('Version', sa.Integer(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Act_UUID'], ['publication_acts.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Act_UUID', 'Version', name='uix_act_version')
    )
    op.create_table('publication_bill_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Bill_UUID', sa.Uuid(), nullable=False),
        sa.Column('Version', sa.Integer(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Bill_UUID'], ['publication_bills.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.PrimaryKeyConstraint('UUID'),
        sa.UniqueConstraint('Bill_UUID', 'Version', name='uix_bill_version')
    )
    op.create_table('publication_environment_states',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Adjust_On_UUID', sa.Uuid(), nullable=True),
        sa.Column('Is_Activated', sa.Boolean(), nullable=False),
        sa.Column('Activated_Datetime', sa.DateTime(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Change_Set', sa.JSON(), nullable=True),
        sa.Column('State', sa.JSON(), nullable=True),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Adjust_On_UUID'], ['publication_environment_states.UUID'], ),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publications',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Module_ID', sa.Integer(), nullable=False),
        sa.Column('Document_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Template_UUID', sa.Uuid(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Module_ID'], ['modules.Module_ID'], ),
        sa.ForeignKeyConstraint(['Template_UUID'], ['publication_templates.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_versions',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_UUID', sa.Uuid(), nullable=False),
        sa.Column('Module_Status_ID', sa.Integer(), nullable=False),
        sa.Column('Environment_UUID', sa.Uuid(), nullable=False),
        sa.Column('Procedure_Type', sa.Unicode(length=50), nullable=False),
        sa.Column('Effective_Date', sa.Date(), nullable=True),
        sa.Column('Announcement_Date', sa.Date(), nullable=True),
        sa.Column('Bill_Metadata', sa.JSON(), nullable=True),
        sa.Column('Bill_Compact', sa.JSON(), nullable=True),
        sa.Column('Procedural', sa.JSON(), nullable=True),
        sa.Column('Act_Metadata', sa.JSON(), nullable=True),
        sa.Column('Locked', sa.Boolean(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Environment_UUID'], ['publication_environments.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Module_Status_ID'], ['module_status_history.ID'], ),
        sa.ForeignKeyConstraint(['Publication_UUID'], ['publications.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_packages',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_Version_UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_Type', sa.Unicode(length=64), nullable=False),
        sa.Column('Validation_Status', sa.Unicode(length=64), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Modified_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Modified_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Modified_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Publication_Version_UUID'], ['publication_versions.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_package_export_state',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Export_Data', sa.JSON(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['Package_UUID'], ['publication_packages.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_package_reports',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Outcome', sa.Unicode(), nullable=False),
        sa.Column('Result', sa.Unicode(), nullable=False),
        sa.Column('Report_Timestamp', sa.DateTime(), nullable=False),
        sa.Column('Messages', sa.UnicodeText(), nullable=False),
        sa.Column('Report_Progress', sa.Unicode(), nullable=True),
        sa.Column('Filename', sa.Unicode(), nullable=False),
        sa.Column('Source_Document', sa.UnicodeText(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Package_UUID'], ['publication_packages.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('publication_package_zips',
        sa.Column('UUID', sa.Uuid(), nullable=False),
        sa.Column('Package_UUID', sa.Uuid(), nullable=False),
        sa.Column('Publication_Filename', sa.Unicode(length=255), nullable=True),
        sa.Column('Filename', sa.Unicode(), nullable=False),
        sa.Column('Binary', sa.LargeBinary(), nullable=False),
        sa.Column('Checksum', sa.String(length=64), nullable=False),
        sa.Column('Latest_Download_Date', sa.DateTime(), nullable=True),
        sa.Column('Latest_Download_By_UUID', sa.Uuid(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['Created_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Latest_Download_By_UUID'], ['Gebruikers.UUID'], ),
        sa.ForeignKeyConstraint(['Package_UUID'], ['publication_packages.UUID'], ),
        sa.PrimaryKeyConstraint('UUID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_package_zips')
    op.drop_table('publication_package_reports')
    op.drop_table('publication_package_export_state')
    op.drop_table('publication_packages')
    op.drop_table('publication_versions')
    op.drop_table('publications')
    op.drop_table('publication_environment_states')
    op.drop_table('publication_bill_versions')
    op.drop_table('publication_act_versions')
    op.drop_table('publication_templates')
    op.drop_table('publication_environments')
    op.drop_table('publication_bills')
    op.drop_table('publication_area_of_jurisdictions')
    op.drop_table('publication_acts')
    # ### end Alembic commands ###
