"""publication_tables

Revision ID: 9418d03d3d96
Revises: 626adccffe91
Create Date: 2024-01-14 13:11:19.797512

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import settings  ## noqa


# revision identifiers, used by Alembic.
revision = "9418d03d3d96"
down_revision = "626adccffe91"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_config",
        sa.Column("ID", sa.Integer(), nullable=False),
        sa.Column("Created_Date", sa.DateTime(), nullable=False),
        sa.Column("Modified_Date", sa.DateTime(), nullable=False),
        sa.Column("Province_ID", sa.String(), nullable=False),
        sa.Column("Authority_ID", sa.String(), nullable=False),
        sa.Column("Submitter_ID", sa.String(), nullable=False),
        sa.Column("Jurisdiction", sa.String(), nullable=False),
        sa.Column("Subjects", sa.String(), nullable=False),
        sa.Column("dso_stop_version", sa.String(), nullable=False),
        sa.Column("dso_tpod_version", sa.String(), nullable=False),
        sa.Column("dso_bhkv_version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_table(
        "publication_bill",
        sa.Column("UUID", sa.Uuid(), nullable=False),
        sa.Column("Version_ID", sa.Integer(), nullable=False),
        sa.Column("Module_ID", sa.Integer(), nullable=False),
        sa.Column("Module_Status_ID", sa.Integer(), nullable=False),
        sa.Column("Bill_Type", sa.Enum("Ontwerp", "Definitief"), nullable=False),
        sa.Column(
            "Document_Type",
            sa.Enum("Omgevingsvisie", "Omgevingsprogramma", "Omgevingsverordening"),
            nullable=False,
        ),
        sa.Column("Bill_Data", sa.JSON(), nullable=True),
        sa.Column("Procedure_Data", sa.JSON(), nullable=True),
        sa.Column("Council_Proposal_File", sa.String(), nullable=True),
        sa.Column("Effective_Date", sa.DateTime(), nullable=True),
        sa.Column("Announcement_Date", sa.DateTime(), nullable=True),
        sa.Column("Created_Date", sa.DateTime(), nullable=True),
        sa.Column("Modified_Date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Module_ID"],
            ["modules.Module_ID"],
        ),
        sa.ForeignKeyConstraint(
            ["Module_Status_ID"],
            ["module_status_history.ID"],
        ),
        sa.PrimaryKeyConstraint("UUID"),
        sa.UniqueConstraint("Module_ID", "Document_Type", "Version_ID"),
    )
    op.create_table(
        "publication_package",
        sa.Column("Bill_UUID", sa.UUID(), nullable=False),
        sa.Column(
            "Package_Event_Type", sa.Enum("Validatie", "Publicatie", "Afbreken"), nullable=False
        ),
        sa.Column("Publication_Filename", sa.String(), nullable=True),
        sa.Column("Announcement_Date", sa.DateTime(), nullable=True),
        sa.Column("Province_ID", sa.String(), nullable=False),
        sa.Column("Submitter_ID", sa.Integer(), nullable=False),
        sa.Column("Authority_ID", sa.Integer(), nullable=False),
        sa.Column("Jurisdiction", sa.String(), nullable=False),
        sa.Column("Subjects", sa.String(), nullable=False),
        sa.Column("dso_stop_version", sa.String(), nullable=False),
        sa.Column("dso_tpod_version", sa.String(), nullable=False),
        sa.Column("dso_bhkv_version", sa.String(), nullable=False),
        sa.Column("UUID", sa.Uuid(), nullable=False),
        sa.Column("Created_Date", sa.DateTime(), nullable=True),
        sa.Column("Modified_Date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Bill_UUID"],
            ["publication_bill.UUID"],
        ),
        sa.PrimaryKeyConstraint("UUID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_package")
    op.drop_table("publication_bill")
    op.drop_table("publication_config")
    # ### end Alembic commands ###
