"""add_gebiedsprogramma_modules

Revision ID: 9598cf20530d
Revises: 1340cf5ef4b1
Create Date: 2023-01-16 03:51:24.881987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

import app.util.sqlalchemy
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9598cf20530d'
down_revision = '1340cf5ef4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Beleidsmodule_Gebiedsprogrammas',
    sa.Column('Beleidsmodule_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Gebiedsprogramma_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidsmodule_UUID'], ['Beleidsmodules.UUID'], name=op.f('FK_Beleidsmodule_Gebiedsprogrammas_Beleidsmodule_UUID')),
    sa.ForeignKeyConstraint(['Gebiedsprogramma_UUID'], ['Gebiedsprogrammas.UUID'], name=op.f('FK_Beleidsmodule_Gebiedsprogrammas_Gebiedsprogramma_UUID')),
    sa.PrimaryKeyConstraint('Beleidsmodule_UUID', 'Gebiedsprogramma_UUID', name=op.f('PK_Beleidsmodule_Gebiedsprogrammas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Beleidsmodule_Gebiedsprogrammas')
    # ### end Alembic commands ###


def dialect_supports_sequences():
    return op._proxy.migration_context.dialect.supports_sequences


def dialect_supports_geometry_index():
    return op._proxy.migration_context.dialect.name == 'mssql'


def create_seq(name):
    if dialect_supports_sequences():
        op.execute(sa.schema.CreateSequence(sa.schema.Sequence(name)))


def drop_seq(name):
    if dialect_supports_sequences():
        op.execute(sa.schema.DropSequence(sa.schema.Sequence(name)))
