""" Ensure Gebruikers.Rol is nullable

Revision ID: 976ee7df9ee4
Revises: a6bc53da87ff
Create Date: 2026-09-09 19:12:19.141420

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = '976ee7df9ee4'
down_revision = 'a6bc53da87ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # This table was not managed by us and therefor not stable between every environment
    # This alter table will force that we will sync all environments
    op.alter_column('Gebruikers', 'Rol',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Nothing to do here as the upgrade was a sync fix
    return
