"""publication_frbr

Revision ID: 9be4a0dd57fb
Revises: ea31e70b1cf4
Create Date: 2024-01-29 13:13:06.361061

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa
from app.core.db import table_metadata  ## noqa
from app.core.settings import settings  ## noqa


# revision identifiers, used by Alembic.
revision = "9be4a0dd57fb"
down_revision = "ea31e70b1cf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_frbr",
        sa.Column("UUID", sa.Uuid(), nullable=False),
        sa.Column("Created_Date", sa.DateTime(), nullable=True),
        sa.Column("Modified_Date", sa.DateTime(), nullable=True),
        sa.Column("bill_work_country", sa.String(), nullable=False),
        sa.Column("bill_work_date", sa.String(), nullable=False),
        sa.Column("bill_work_misc", sa.String(), nullable=True),
        sa.Column("bill_expression_lang", sa.String(), nullable=False),
        sa.Column("bill_expression_date", sa.DateTime(), nullable=False),
        sa.Column("bill_expression_version", sa.String(), nullable=False),
        sa.Column("bill_expression_misc", sa.String(), nullable=True),
        sa.Column("act_work_country", sa.String(), nullable=False),
        sa.Column("act_work_date", sa.String(), nullable=False),
        sa.Column("act_work_misc", sa.String(), nullable=True),
        sa.Column("act_expression_lang", sa.String(), nullable=False),
        sa.Column("act_expression_date", sa.DateTime(), nullable=False),
        sa.Column("act_expression_version", sa.String(), nullable=False),
        sa.Column("act_expression_misc", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("UUID"),
    )
    op.add_column("publication_packages", sa.Column("Validated_At", sa.DateTime(), nullable=True))
    op.add_column("publication_packages", sa.Column("FRBR_UUID", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "publication_packages", "publication_frbr", ["FRBR_UUID"], ["UUID"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "publication_packages", type_="foreignkey")
    op.drop_column("publication_packages", "FRBR_UUID")
    op.drop_column("publication_packages", "Validated_At")
    op.drop_table("publication_frbr")
    # ### end Alembic commands ###
