"""Adding werkingsgebieden validity

Revision ID: a26a0e7d8262
Revises: b23b7c75f6b2
Create Date: 2023-09-08 08:28:53.005629

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.core.settings import Settings
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 


# revision identifiers, used by Alembic.
revision = 'a26a0e7d8262'
down_revision = 'b23b7c75f6b2'
branch_labels = None
depends_on = None

# Werkingsgebied table is only touched on local dev environments
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    settings = Settings()
    if not settings.LOCAL_DEVELOPMENT_MODE:
        return
    op.add_column('Werkingsgebieden', sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False))
    op.add_column('Werkingsgebieden', sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    settings = Settings()
    if not settings.LOCAL_DEVELOPMENT_MODE:
        return
    op.drop_column('Werkingsgebieden', 'Eind_Geldigheid')
    op.drop_column('Werkingsgebieden', 'Begin_Geldigheid')
    # ### end Alembic commands ###
