"""Multiple roles for objects and module_objects

Revision ID: a6bc53da87ff
Revises: 80143fa75c0b
Create Date: 2026-09-01 07:12:25.391715

"""

import sqlalchemy as sa

from alembic import op
from app.core.db import table_metadata  ## noqa
from app.core.settings import Settings

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa

settings = Settings()


# revision identifiers, used by Alembic.
revision = "a6bc53da87ff"
down_revision = "80143fa75c0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("module_objects", sa.Column("Roles", sa.JSON(), nullable=True))
    op.add_column("objects", sa.Column("Roles", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objects", "Roles")
    op.drop_column("module_objects", "Roles")
    # ### end Alembic commands ###
