"""Adding change log

Revision ID: b23b7c75f6b2
Revises: 9978738fb35f
Create Date: 2023-06-05 12:56:42.388352

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = 'b23b7c75f6b2'
down_revision = '9978738fb35f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
        sa.Column('ID', sa.Integer(), nullable=False),
        sa.Column('Object_Type', sa.Unicode(length=25), nullable=True),
        sa.Column('Object_ID', sa.Integer(), nullable=True),
        sa.Column('Created_Date', sa.DateTime(), nullable=False),
        sa.Column('Created_By_UUID', sa.Uuid(), nullable=False),
        sa.Column('Action_Type', sa.Unicode(), nullable=False),
        sa.Column('Action_Data', sa.Unicode(), nullable=True),
        sa.Column('Before', sa.Unicode(), nullable=True),
        sa.Column('After', sa.Unicode(), nullable=True),
        sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_log')
    # ### end Alembic commands ###
