""" Adding onderverdeling object

Revision ID: b5dae5845174
Revises: d9ad1aa2d0ce
Create Date: 2025-03-04 14:54:45.795056

"""
from alembic import op
import sqlalchemy as sa
from app.extensions.source_werkingsgebieden import geometry  ## noqa
from app.extensions.source_werkingsgebieden.geometry import Geometry  ## noqa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 


# revision identifiers, used by Alembic.
revision = 'b5dae5845174'
down_revision = 'd9ad1aa2d0ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_objects', sa.Column('Onderverdelingen', sa.JSON(), nullable=True))
    op.add_column('objects', sa.Column('Onderverdelingen', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Onderverdelingen')
    op.drop_column('module_objects', 'Onderverdelingen')
    # ### end Alembic commands ###
