"""empty message

Revision ID: cad90da70a44
Revises: 07fb2e0a7f03
Create Date: 2023-03-20 12:51:51.291994

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = 'cad90da70a44'
down_revision = '07fb2e0a7f03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_objects', sa.Column('IDMS_Link', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('IDMS_Link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'IDMS_Link')
    op.drop_column('module_objects', 'IDMS_Link')
    # ### end Alembic commands ###
