"""empty message

Revision ID: eb6126c067be
Revises: 2dbf768b0401
Create Date: 2023-05-15 16:39:57.125950

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import settings  ## noqa 



# revision identifiers, used by Alembic.
revision = 'eb6126c067be'
down_revision = '2dbf768b0401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acknowledged_relations', sa.Column('Version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acknowledged_relations', 'Version')
    # ### end Alembic commands ###
