"""Input GEO Onderverdeling Added Source Title

Revision ID: fd9b32be5c00
Revises: 276828ec0bcc
Create Date: 2026-01-13 12:48:07.783734

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = 'fd9b32be5c00'
down_revision = '276828ec0bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_objects', sa.Column('Source_Title', sa.Unicode(), nullable=True))
    op.add_column('objects', sa.Column('Source_Title', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Source_Title')
    op.drop_column('module_objects', 'Source_Title')
    # ### end Alembic commands ###
