"""Input GEO Onderverdeling Added Source Title

Revision ID: ffce58fd473e
Revises: fd9b32be5c00
Create Date: 2026-01-13 13:27:13.212321

"""
from alembic import op
import sqlalchemy as sa

# We need these to load all sqlalchemy tables
from app.main import app  ## noqa 
from app.core.db import table_metadata  ## noqa 
from app.core.settings import Settings  ## noqa

settings = Settings()



# revision identifiers, used by Alembic.
revision = 'ffce58fd473e'
down_revision = 'fd9b32be5c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_objects', sa.Column('Source_UUID', sa.Uuid(), nullable=True))
    op.add_column('objects', sa.Column('Source_UUID', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'Source_UUID')
    op.drop_column('module_objects', 'Source_UUID')
    op.drop_table('Onderverdeling')
    # ### end Alembic commands ###
