from .create_publication import CreatePublicationEndpointResolver
from .detail_publication import DetailPublicationEndpointResolver
from .edit_publication import EditPublicationEndpointResolver
from .list_publications import ListPublicationsEndpointResolver