id: ambitie
object_type: ambitie

api:
  routers:
    - prefix: /ambities
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: ambitie_get
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: ambitie_basic
            allowed_filter_columns:
              - Title
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: ambitie_get
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: ambitie_get
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidsdoel
        - resolver: list_werkingsgebieden
          resolver_data:
            path: /werkingsgebieden/{lineage_id}
        - resolver: overwrite_werkingsgebieden
          resolver_data:
            path: /werkingsgebieden/{lineage_id}
    - prefix: /ambitie/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: ambitie_static_patch
    - prefix: /ambitie/acknowledged-relations/{lineage_id}
      endpoints:
        - resolver: list_acknowledged_relations
        - resolver: request_acknowledged_relation
          resolver_data:
            allowed_object_types:
              - ambitie
              - beleidsdoel
        - resolver: edit_acknowledged_relation
          resolver_data:
            path: /edit
    - prefix: /modules/{module_id}/object/ambitie
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: ambitie_patch
            response_model: ambitie_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: ambitie_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: ambitie_get
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: ambitie_get

fields:
  title:
    name: Title
    type: str
    column: title
    validators: []
    formatters: []
  description:
    name: Description
    type: str
    column: description
    validators: []
    formatters: []
  weblink:
    name: Weblink
    type: str
    column: weblink
    validators: []
    formatters: []
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  ambitie_short:
    name: AmbitieShort
    fields:
      object_id:
      uuid:
      title:
      description:
  ambitie_basic:
    name: AmbitieBasic
    fields:
      object_id:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      weblink:
    services:
      extended_user:
        fields_map:
          - from_field: Created_By_UUID
            to_field: Created_By
            model_id: gebruikers_short
          - from_field: Modified_By_UUID
            to_field: Modified_By
            model_id: gebruikers_short
  ambitie_get:
    name: AmbitieGet
    fields:
      object_id:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      weblink:
      start_validity:
      end_validity:
    services:
      werkingsgebieden:
        to_field: Werkingsgebieden
        model_id: werkingsgebied
      relations:
        objects:
          - object_type: beleidsdoel
            object_id: beleidsdoel
            to_field: "Beleidsdoelen"
            model_id: beleidsdoel_short
            wrapped_with_relation_data: false
      extended_user:
        fields_map:
          - from_field: Created_By_UUID
            to_field: Created_By
            model_id: gebruikers_short
          - from_field: Modified_By_UUID
            to_field: Modified_By
            model_id: gebruikers_short
          - from_field: Owner_1_UUID
            to_field: Owner_1
            model_id: gebruikers_short
          - from_field: Owner_2_UUID
            to_field: Owner_2
            model_id: gebruikers_short
  ambitie_patch:
    name: AmbitiePatch
    fields:
      title:
        default: none
        optional: True
      description:
        default: none
        optional: True
      weblink:
        default: none
        optional: True
  ambitie_static_patch:
    name: AmbitieStaticPatch
    fields:
      owner_1_uuid:
        default: none
        optional: True
      owner_2_uuid:
        default: none
        optional: True
  ambitie_uuid:
    name: AmbitieUUID
    fields:
      object_id:
      uuid:
