id: ambitie
object_type: ambitie

sort_allowed_columns: &sort_allowed_columns
  - Object_ID
  - Title
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_columns

api:
  routers:
    - prefix: /ambities
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: ambitie_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_title
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: ambitie_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: ambitie_full
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: ambitie_full
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidsdoel
    - prefix: /ambitie/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: ambitie_static_post
            result_model: ambitie_static_post_validated
    - prefix: /modules/{module_id}/object/ambitie
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: ambitie_patch
            response_model: ambitie_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: ambitie_extended
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: ambitie_full
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: ambitie_full
    - prefix: /modules/object/ambitie
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
    - prefix: /revisions/{module_id}/ambitie/version/{object_uuid}
      endpoints:
        - resolver: module_object_version
          resolver_data:
            response_model: ambitie_full
            minimum_status: 'Ontwerp GS Concept'
            require_auth: False

fields:
  title:
    name: Title
    type: str
    column: title
    validators:
      - id: none_to_default_value
  description:
    name: Description
    type: str
    column: description
    validators:
      - id: none_to_default_value
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
    validators:
      - id: none_to_default_value
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number
    validators:
      - id: none_to_default_value

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true
  portfolio_holder_1_uuid:
    name: Portfolio_Holder_1_UUID
    type: uuid
    column: portfolio_holder_1_uuid
    optional: true
  portfolio_holder_2_uuid:
    name: Portfolio_Holder_2_UUID
    type: uuid
    column: portfolio_holder_1_uuid
    optional: true
  client_1_uuid:
    name: Client_1_UUID
    type: uuid
    column: client_1_uuid
    optional: true

models:
  ambitie_minimal:
    name: AmbitieMinimal
    fields:
      object_type:
      object_id:
      uuid:
      title:
  ambitie_basic:
    name: AmbitieBasic
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      start_validity:
      end_validity:
    services:
      next_object_version:
        to_field: Next_Version
  ambitie_extended:
    name: AmbitieExtended
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
          - to_field: Portfolio_Holder_1
            model_id: user_short
          - to_field: Portfolio_Holder_2
            model_id: user_short
          - to_field: Client_1
            model_id: user_short
  ambitie_full:
    name: AmbitieFull
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
      - beleidsdoel_minimal
    services:
      next_object_version:
        to_field: Next_Version
      public_revisions:
        to_field: Public_Revisions
      insert_assets:
        fields:
          - Description
      resolve_child_objects_via_hierarchy_listener:
        to_field: Hierarchy_Children
      relations:
        objects:
          - object_type: beleidsdoel
            object_id: beleidsdoel
            to_field: "Beleidsdoelen"
            model_id: beleidsdoel_minimal
            wrapped_with_relation_data: true
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
          - to_field: Portfolio_Holder_1
            model_id: user_short
          - to_field: Portfolio_Holder_2
            model_id: user_short
          - to_field: Client_1
            model_id: user_short
  ambitie_patch:
    name: AmbitiePatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      description:
        default: none
        optional: true
        validators:
          - id: html
          - id: image
            data:
              max_width: 1500
              max_height: 2500
              max_kb: 800
    services:
      extract_assets:
        fields:
          - Description
  ambitie_static_post:
    name: AmbitieStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
      portfolio_holder_1_uuid:
        default: none
        optional: true
      portfolio_holder_2_uuid:
        default: none
        optional: true
      client_1_uuid:
        default: none
        optional: true
  ambitie_static_post_validated:
    name: AmbitieStaticPostValidated
    static_only: true
    model_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
      - id: not_equal_root
        data:
          fields:
            - Portfolio_Holder_1_UUID
            - Portfolio_Holder_2_UUID
          allow_none: True
          error_message: Portfolio Holders should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
      portfolio_holder_1_uuid:
        default: none
        optional: true
      portfolio_holder_2_uuid:
        default: none
        optional: true
      client_1_uuid:
        default: none
        optional: true
  ambitie_uuid:
    name: AmbitieUUID
    fields:
      object_id:
      uuid:
  ambitie_module_validate:
    name: AmbitieModuleValidate
    fields:
      title:
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      description:
        validators:
          - id: length
            data:
              min: 3
          - id: html
