id: beleidsregel
object_type: beleidsregel

api:
  routers:
    - prefix: /beleidsregels
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: beleidsregel_get
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: beleidsregel_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: beleidsregel_get
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: beleidsregel_get
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidskeuze
    - prefix: /beleidsregel/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: beleidsregel_static_post
            result_model: beleidsregel_static_post
    - prefix: /modules/{module_id}/object/beleidsregel
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: beleidsregel_patch
            response_model: beleidsregel_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: beleidsregel_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: beleidsregel_get
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: beleidsregel_get
    - prefix: /modules/objects/beleidsregel
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
            response_model: beleidsregel_short

fields:
  title:
    name: Title
    type: str
    column: title
  description:
    name: Description
    type: str
    column: description
  weblink:
    name: Weblink
    type: str
    column: weblink
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true
  portfolio_holder_1_uuid:
    name: Portfolio_Holder_1_UUID
    type: uuid
    column: portfolio_holder_1_uuid
    optional: true
  portfolio_holder_2_uuid:
    name: Portfolio_Holder_2_UUID
    type: uuid
    column: portfolio_holder_1_uuid
    optional: true
  client_1_uuid:
    name: Client_1_UUID
    type: uuid
    column: client_1_uuid
    optional: true

models:
  beleidsregel_short:
    name: BeleidsregelShort
    fields:
      object_type:
      object_id:
      uuid:
      title:
  beleidsregel_basic:
    name: BeleidsregelBasic
    fields:
      object_id:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      weblink:
      start_validity:
      end_validity:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
  beleidsregel_get:
    name: BeleidsregelGet
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      weblink:
      description:
      start_validity:
      end_validity:
    services:
      insert_assets:
        fields:
          - Description
      relations:
        objects:
          - object_type: beleidskeuze
            object_id: beleidskeuze
            to_field: "Beleidskeuzes"
            model_id: beleidskeuze_short
            wrapped_with_relation_data: true
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
          - to_field: Portfolio_Holder_1
            model_id: gebruikers_short
          - to_field: Portfolio_Holder_2
            model_id: gebruikers_short
          - to_field: Client_1
            model_id: gebruikers_short
  beleidsregel_patch:
    name: BeleidsregelPatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        default: none
        optional: true
        validators:
          - id: plain_text
      description:
        default: none
        optional: true
        validators:
          - id: plain_text
    services:
      extract_assets:
        fields:
          - Description
  beleidsregel_static_post:
    name: BeleidsregelStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
      portfolio_holder_1_uuid:
        default: none
        optional: true
      portfolio_holder_2_uuid:
        default: none
        optional: true
      client_1_uuid:
        default: none
        optional: true
  beleidsregel_uuid:
    name: BeleidsregelUUID
    fields:
      object_id:
      uuid:
