id: beleidsdoel
object_type: beleidsdoel

api:
  routers:
    - prefix: /beleidsdoelen
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: beleidsdoel_get
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: beleidsdoel_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: beleidsdoel_get
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: beleidsdoel_get
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - ambitie
              - beleidskeuze
    - prefix: /beleidsdoel/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: beleidsdoel_static_patch
    - prefix: /modules/{module_id}/object/beleidsdoel
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: beleidsdoel_patch
            response_model: beleidsdoel_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: beleidsdoel_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: beleidsdoel_get
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: beleidsdoel_get

fields:
  title:
    name: Title
    type: str
    column: title
  description:
    name: Description
    type: str
    column: description
  weblink:
    name: Weblink
    type: str
    column: weblink
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  beleidsdoel_short:
    name: BeleidsdoelShort
    fields:
      object_type:
      object_id:
      uuid:
      title:
  beleidsdoel_basic:
    name: BeleidsdoelBasic
    fields:
      object_id:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      weblink:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
  beleidsdoel_get:
    name: BeleidsdoelGet
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      weblink:
      start_validity:
      end_validity:
    services:
      relations:
        objects:
          - object_type: ambitie
            object_id: ambitie
            to_field: "Ambities"
            model_id: ambitie_short
            wrapped_with_relation_data: true
          - object_type: beleidskeuze
            object_id: beleidskeuze
            to_field: "Beleidskeuzes"
            model_id: beleidskeuze_short
            wrapped_with_relation_data: true
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
  beleidsdoel_patch:
    name: BeleidsdoelPatch
    fields:
      title:
        default: none
        optional: True
      description:
        default: none
        optional: True
      weblink:
        default: none
        optional: True
  beleidsdoel_static_patch:
    name: BeleidsdoelStaticPatch
    fields:
      owner_1_uuid:
        default: none
        optional: True
      owner_2_uuid:
        default: none
        optional: True
  beleidsdoel_uuid:
    name: BeleidsdoelUUID
    fields:
      object_id:
      uuid:
