id: document
object_type: document

sort_allowed_columns: &sort_allowed_columns
  - Object_ID
  - Title
  - Filename
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_columns

api:
  routers:
    - prefix: /documenten
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: document_basic
            allowed_filter_columns:
              - Title
              - Filename
            sort: *sort_default_title
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: document_basic
            allowed_filter_columns:
              - Title
              - Filename
            sort: *sort_default_modified_date
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: document_full
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: document_full
    - prefix: /document/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: document_static_post
            result_model: document_static_post_validated
    - prefix: /modules/{module_id}/object/document
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: document_patch
            response_model: document_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: document_extended
            allowed_filter_columns:
              - Title
              - Filename
            sort: *sort_default_modified_date
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: document_full
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: document_full
    - prefix: /modules/object/document
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
            response_model: document_minimal
            sort: *sort_default_title
    - prefix: /revisions/{module_id}/document/version/{object_uuid}
      endpoints:
        - resolver: module_object_version
          resolver_data:
            response_model: document_full
            minimum_status: 'Ontwerp GS Concept'
            require_auth: False

fields:
  title:
    name: Title
    type: str
    column: title
    validators:
      - id: none_to_default_value
  filename:
    name: Filename
    type: str
    column: filename
    validators:
      - id: none_to_default_value
  description:
    name: Description
    type: str
    column: description
    validators:
      - id: none_to_default_value
  file_uuid:
    name: File_UUID
    type: uuid
    column: file_uuid
    validators:
      - id: none_to_default_value
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
    validators:
      - id: none_to_default_value
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number
    validators:
      - id: none_to_default_value

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  document_minimal:
    name: DocumentMinimal
    fields:
      object_type:
      object_id:
      uuid:
      title:
      filename:
  document_basic:
    name: DocumentBasic
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      filename:
      file_uuid:
      start_validity:
      end_validity:
  document_extended:
    name: DocumentExtended
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      filename:
      file_uuid:
      start_validity:
      end_validity:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  document_full:
    name: DocumentFull
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      filename:
      description:
      start_validity:
      end_validity:
      file_uuid:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: File
            model_id: storage_file_basic
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  document_patch:
    name: DocumentPatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      filename:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: filename
      description:
        default: none
        optional: true
      file_uuid:
        default: none
        optional: true
  document_static_post:
    name: DocumentStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  document_static_post_validated:
    name: DocumentStaticPostValidated
    static_only: true
    model_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
  document_uuid:
    name: DocumentUUID
    fields:
      object_id:
      uuid:
