id: nationaal_belang
object_type: nationaal_belang

api:
  routers:
    - prefix: /nationaal-belang
      endpoints:
        - resolver: atemporal_create_object
          resolver_data:
            request_model: nationaal_belang_create
            response_model: nationaal_belang_uuid
        - resolver: atemporal_edit_object
          resolver_data:
            path: /{lineage_id}
            request_model: nationaal_belang_edit
        - resolver: atemporal_delete_object
          resolver_data:
            path: /{lineage_id}
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: nationaal_belang_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: nationaal_belang_full
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidskeuze
    - prefix: /nationaal-belang/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: nationaal_belang_static_post
            result_model: nationaal_belang_static_post_validated
            response_model: nationaal_belang_basic

fields:
  title:
    name: Title
    type: str
    column: title
  weblink:
    name: Weblink
    type: str
    column: weblink

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  nationaal_belang_minimal:
    name: NationaalBelangMinimal
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
  nationaal_belang_basic:
    name: NationaalBelangBasic
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
  nationaal_belang_extended:
    name: NationaalBelangExtended
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
  nationaal_belang_full:
    name: NationaalBelangFull
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
      start_validity:
      end_validity:
    services:
      relations:
        objects:
          - object_type: beleidskeuze
            object_id: beleidskeuze
            to_field: "Beleidskeuzes"
            model_id: beleidskeuze_minimal
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
  nationaal_belang_create:
    name: NationaalBelangCreate
    fields:
      title:
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        optional: true
        validators:
          - id: plain_text
      owner_1_uuid:
      owner_2_uuid:
  nationaal_belang_edit:
    name: NationaalBelangEdit
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        default: none
        optional: true
        validators:
          - id: plain_text
  nationaal_belang_static_post:
    name: NationaalBelangStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  nationaal_belang_static_post_validated:
    name: NationaalBelangStaticPostValidated
    static_only: true
    root_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
  nationaal_belang_uuid:
    name: NationaalBelangUUID
    fields:
      object_id:
      uuid:
