id: belang
object_type: belang

api:
  routers:
    - prefix: /belang
      endpoints:
        - resolver: atemporal_create_object
          resolver_data:
            request_model: belang_create
            response_model: belang_uuid
        - resolver: atemporal_edit_object
          resolver_data:
            path: /{lineage_id}
            request_model: belang_edit
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: belang_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: belang_get
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidskeuze
    - prefix: /belang/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: belang_static_edit

fields:
  title:
    name: Title
    type: str
    column: title
  weblink:
    name: Weblink
    type: str
    column: weblink

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  belang_basic:
    name: BelangBasic
    fields:
      object_type:
      object_id:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
  belang_get:
    name: BelangGet
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
      start_validity:
      end_validity:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
  belang_create:
    name: BelangCreate
    fields:
      title:
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        optional: true
        validators:
          - id: plain_text
      owner_1_uuid:
      owner_2_uuid:
  belang_edit:
    name: BelangEdit
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        default: none
        optional: true
        validators:
          - id: plain_text
  belang_static_edit:
    name: BelangStaticEdit
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  belang_uuid:
    name: BelangUUID
    fields:
      object_id:
      uuid:
