id: programma_algemeen
object_type: programma_algemeen

sort_allowed_columns: &sort_allowed_columns
  - Object_ID
  - Title
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_columns

api:
  routers:
    - prefix: /programmas-algemeen
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: programma_algemeen_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_title
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: programma_algemeen_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: programma_algemeen_full
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: programma_algemeen_full
    - prefix: /programma-algemeen/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: programma_algemeen_static_post
            result_model: programma_algemeen_static_post_validated
    - prefix: /modules/{module_id}/object/programma-algemeen
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: programma_algemeen_patch
            response_model: programma_algemeen_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: programma_algemeen_extended
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: programma_algemeen_full
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: programma_algemeen_full
    - prefix: /modules/object/programma-algemeen
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
            response_model: programma_algemeen_minimal
            sort: *sort_default_title
    - prefix: /revisions/{module_id}/programma-algemeen/version/{object_uuid}
      endpoints:
        - resolver: module_object_version
          resolver_data:
            response_model: programma_algemeen_full
            minimum_status: 'Ontwerp GS Concept'
            require_auth: False

fields:
  title:
    name: Title
    type: str
    column: title
    validators:
      - id: none_to_default_value
  description:
    name: Description
    type: str
    column: description
    validators:
      - id: none_to_default_value
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
    validators:
      - id: none_to_default_value
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number
    validators:
      - id: none_to_default_value

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  programma_algemeen_minimal:
    name: ProgrammaAlgemeenMinimal
    fields:
      object_type:
      object_id:
      uuid:
      title:
  programma_algemeen_basic:
    name: ProgrammaAlgemeenBasic
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      start_validity:
      end_validity:
    dependency_model_ids:
      - next_object_validities
    services:
      computed_fields:
        - batch_next_object_version
  programma_algemeen_extended:
    name: ProgrammaAlgemeenExtended
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  programma_algemeen_full:
    name: ProgrammaAlgemeenFull
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
      - next_object_validities
      - public_module_object_revision
    services:
      computed_fields:
        - next_object_version
        - public_revisions
      insert_assets:
        fields:
          - Description
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  programma_algemeen_patch:
    name: ProgrammaAlgemeenPatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      description:
        default: none
        optional: true
        validators:
          - id: html
          - id: image
            data:
              max_width: 1500
              max_height: 2500
              max_kb: 800
    services:
      extract_assets:
        fields:
          - Description
  programma_algemeen_static_post:
    name: ProgrammaAlgemeenStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  programma_algemeen_static_post_validated:
    name: ProgrammaAlgemeenStaticPostValidated
    static_only: true
    model_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
  programma_algemeen_uuid:
    name: ProgrammaAlgemeenUUID
    fields:
      object_id:
      uuid:
