id: werkingsgebied
object_type: werkingsgebied

sort_allowed_columns: &sort_allowed_columns
  - Object_ID
  - Title
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_columns

api:
  routers:
    - prefix: /werkingsgebieden
      endpoints:
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: werkingsgebied_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_title
        - resolver: valid_list_lineage_tree
          resolver_data:
            path: /valid/{lineage_id}
            response_model: werkingsgebied_basic
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: werkingsgebied_full
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: werkingsgebied_full
    - prefix: /werkingsgebied/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: werkingsgebied_static_post
            result_model: werkingsgebied_static_post_validated
    - prefix: /modules/{module_id}/object/werkingsgebied
      endpoints:
        - resolver: module_patch_object
          resolver_data:
            path: /{lineage_id}
            request_model: werkingsgebied_patch
            response_model: werkingsgebied_uuid
        - resolver: module_list_lineage_tree
          resolver_data:
            path: /{lineage_id}
            response_model: werkingsgebied_extended
            allowed_filter_columns:
              - Title
            sort: *sort_default_modified_date
        - resolver: module_object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: werkingsgebied_full
        - resolver: module_object_version
          resolver_data:
            path: /version/{object_uuid}
            response_model: werkingsgebied_full
    - prefix: /modules/object/werkingsgebied
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
    - prefix: /revisions/{module_id}/werkingsgebied/version/{object_uuid}
      endpoints:
        - resolver: module_object_version
          resolver_data:
            response_model: werkingsgebied_full
            minimum_status: 'Ontwerp GS Concept'
            require_auth: False

fields:
  title:
    name: Title
    type: str
    column: title
    validators:
      - id: none_to_default_value
  description:
    name: Description
    type: str
    column: description
    validators:
      - id: none_to_default_value
  area_uuid:
    name: Area_UUID
    type: uuid
    column: area_uuid
    validators:
      - id: none_to_default_value
  onderverdelingen:
    name: Onderverdelingen
    type: list_str
    column: onderverdelingen
    validators:
      - id: none_to_default_value
  idms_link:
    name: IDMS_Link
    type: str
    column: idms_link
    validators:
      - id: none_to_default_value
  decision_number:
    name: Decision_Number
    type: str
    column: decision_number
    validators:
      - id: none_to_default_value

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  werkingsgebied_minimal:
    name: WerkingsgebiedMinimal
    fields:
      object_type:
      object_id:
      uuid:
      title:
  werkingsgebied_basic:
    name: WerkingsgebiedBasic
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      area_uuid:
      onderverdelingen:
      start_validity:
      end_validity:
  werkingsgebied_extended:
    name: WerkingsgebiedExtended
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      area_uuid:
      onderverdelingen:
      start_validity:
      end_validity:
    dependency_model_ids:
      - user_short
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  werkingsgebied_full:
    name: WerkingsgebiedFull
    fields:
      object_id:
      code:
      uuid:
      adjust_on:
      created_date:
      modified_date:
      title:
      description:
      start_validity:
      end_validity:
      area_uuid:
    dependency_model_ids:
      - user_short
      - area_basic
    services:
      werkingsgebied_related_objects:
        to_field: Related_Objects
      foreign_keys_extender:
        fields_map:
          - to_field: Area
            model_id: area_basic
          - to_field: Created_By
            model_id: user_short
          - to_field: Modified_By
            model_id: user_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: user_short
          - to_field: Owner_2
            model_id: user_short
  werkingsgebied_patch:
    name: WerkingsgebiedPatch
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      description:
        default: none
        optional: true
      area_uuid:
        default: none
        optional: true
    services:
      change_area:
        fields:
          - Area_UUID
  werkingsgebied_static_post:
    name: WerkingsgebiedStaticPost
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  werkingsgebied_static_post_validated:
    name: WerkingsgebiedStaticPostValidated
    static_only: true
    model_validators:
      - id: not_equal_root
        data:
          fields:
            - Owner_1_UUID
            - Owner_2_UUID
          allow_none: True
          error_message: Owners should vary
    fields:
      owner_1_uuid:
      owner_2_uuid:
        default: none
        optional: true
  werkingsgebied_uuid:
    name: WerkingsgebiedUUID
    fields:
      object_id:
      uuid:
