id: wettelijke_taak
object_type: wettelijke_taak

api:
  routers:
    - prefix: /wettelijke-taak
      endpoints:
        - resolver: atemporal_create_object
          resolver_data:
            request_model: wettelijke_taak_create
            response_model: wettelijke_taak_uuid
        - resolver: atemporal_edit_object
          resolver_data:
            path: /{lineage_id}
            request_model: wettelijke_taak_edit
        - resolver: valid_list_lineages
          resolver_data:
            path: /valid
            response_model: wettelijke_taak_basic
            allowed_filter_columns:
              - Title
              - Weblink
        - resolver: object_latest
          resolver_data:
            path: /latest/{lineage_id}
            response_model: wettelijke_taak_get
        - resolver: list_relations
          resolver_data:
            path: /relations/{lineage_id}
        - resolver: overwrite_relations
          resolver_data:
            path: /relations/{lineage_id}
            allowed_object_types_relations:
              - beleidskeuze
              - verplicht_programma
    - prefix: /wettelijke-taak/static/{lineage_id}
      endpoints:
        - resolver: edit_object_static
          resolver_data:
            request_model: wettelijke_taak_static_edit
            result_model: wettelijke_taak_static_edit
    - prefix: /modules/objects/wettelijke-taak
      endpoints:
        - resolver: list_active_module_objects
          resolver_data:
            path: /active/{lineage_id}
            response_model: wettelijke_taak_short

fields:
  title:
    name: Title
    type: str
    column: title
  weblink:
    name: Weblink
    type: str
    column: weblink

  # Statics
  owner_1_uuid:
    name: Owner_1_UUID
    type: uuid
    column: owner_1_uuid
    optional: true
  owner_2_uuid:
    name: Owner_2_UUID
    type: uuid
    column: owner_2_uuid
    optional: true

models:
  wettelijke_taak_short:
    name: WettelijkeTaakShort
    fields:
      object_type:
      object_id:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
  wettelijke_taak_basic:
    name: WettelijkeTaakBasic
    fields:
      object_type:
      object_id:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
    services:
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
  wettelijke_taak_get:
    name: WettelijkeTaakGet
    fields:
      object_type:
      object_id:
      code:
      uuid:
      created_date:
      modified_date:
      title:
      weblink:
      start_validity:
      end_validity:
    services:
      relations:
        objects:
          - object_type: wettelijke_taak
            object_id: wettelijke_taak
            to_field: "WettelijkeTaken"
            model_id: wettelijke_taak_short
          - object_type: beleidskeuze
            object_id: beleidskeuze
            to_field: "Beleidskeuzes"
            model_id: beleidskeuze_short
            wrapped_with_relation_data: true
      foreign_keys_extender:
        fields_map:
          - to_field: Created_By
            model_id: gebruikers_short
          - to_field: Modified_By
            model_id: gebruikers_short
      static_foreign_keys_extender:
        fields_map:
          - to_field: Owner_1
            model_id: gebruikers_short
          - to_field: Owner_2
            model_id: gebruikers_short
  wettelijke_taak_create:
    name: WettelijkeTaakCreate
    fields:
      title:
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        optional: true
        validators:
          - id: plain_text
      owner_1_uuid:
      owner_2_uuid:
  wettelijke_taak_edit:
    name: WettelijkeTaakEdit
    fields:
      title:
        default: none
        optional: true
        validators:
          - id: length
            data:
              min: 3
              max: 200
          - id: plain_text
      weblink:
        default: none
        optional: true
        validators:
          - id: plain_text
  wettelijke_taak_static_edit:
    name: WettelijkeTaakStaticEdit
    static_only: true
    fields:
      owner_1_uuid:
        default: none
        optional: true
      owner_2_uuid:
        default: none
        optional: true
  wettelijke_taak_uuid:
    name: WettelijkeTaakUUID
    fields:
      object_id:
      uuid:
