"""Initial database setup as prod already is

Revision ID: c29ae17f67fa
Revises: 
Create Date: 2022-02-10 15:53:06.037978

"""
from alembic import op
import sqlalchemy as sa
import Utils
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c29ae17f67fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gebruikers',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Gebruikersnaam', sa.Unicode(length=50), nullable=False),
    sa.Column('Wachtwoord', sa.Unicode(), nullable=True),
    sa.Column('Rol', sa.Unicode(length=50), nullable=False),
    sa.Column('Email', sa.Unicode(length=265), nullable=True),
    sa.Column('Status', sa.Unicode(length=50), server_default=sa.text("('Actief')"), nullable=True),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Ambities',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Belangen',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Type', sa.Unicode(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidsdoelen',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidskeuzes',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Eigenaar_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Eigenaar_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Portefeuillehouder_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Portefeuillehouder_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Opdrachtgever', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Titel', sa.Unicode(), nullable=False),
    sa.Column('Omschrijving_Keuze', sa.Unicode(), nullable=True),
    sa.Column('Omschrijving_Werking', sa.Unicode(), nullable=True),
    sa.Column('Provinciaal_Belang', sa.Unicode(), nullable=True),
    sa.Column('Aanleiding', sa.Unicode(), nullable=True),
    sa.Column('Afweging', sa.Unicode(), nullable=True),
    sa.Column('Besluitnummer', sa.Unicode(), nullable=True),
    sa.Column('Tags', sa.Unicode(), nullable=True),
    sa.Column('Aanpassing_Op', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Status', sa.Unicode(length=50), nullable=False),
    sa.Column('Weblink', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Aanpassing_Op'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_2'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Opdrachtgever'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_2'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidsmodules',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Besluit_Datum', sa.DateTime(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidsprestaties',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidsregels',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=500), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Externe_URL', sa.String(length=300, collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Themas',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Verordeningen',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Portefeuillehouder_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Portefeuillehouder_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Eigenaar_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Eigenaar_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Opdrachtgever', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Titel', sa.Unicode(), nullable=True),
    sa.Column('Inhoud', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Status', sa.Unicode(length=50), nullable=False),
    sa.Column('Type', sa.Unicode(), nullable=False),
    sa.Column('Gebied', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Volgnummer', sa.Unicode(), nullable=False),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_2'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Opdrachtgever'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_2'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Verordeningstructuur',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(length=150), nullable=False),
    sa.Column('Structuur', mssql.XML(), nullable=False),
    sa.Column('Status', sa.Unicode(length=50), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Werkingsgebieden',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Werkingsgebied', sa.Unicode(), nullable=False),
    sa.Column('symbol', sa.Unicode(length=265), nullable=True),
    sa.Column('SHAPE', Utils.sqlalchemy.Geometry(), nullable=False),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidskeuze_Ambities',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Ambitie_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Ambitie_UUID'], ['Ambities.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Ambitie_UUID')
    )
    op.create_table('Beleidskeuze_Belangen',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Belang_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Belang_UUID'], ['Belangen.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Belang_UUID')
    )
    op.create_table('Beleidskeuze_Beleidsdoelen',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Beleidsdoel_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidsdoel_UUID'], ['Beleidsdoelen.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Beleidsdoel_UUID')
    )
    op.create_table('Beleidskeuze_Beleidsprestaties',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Beleidsprestatie_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidsprestatie_UUID'], ['Beleidsprestaties.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Beleidsprestatie_UUID')
    )
    op.create_table('Beleidskeuze_Beleidsregels',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Beleidsregel_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidsregel_UUID'], ['Beleidsregels.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Beleidsregel_UUID')
    )
    op.create_table('Beleidskeuze_Themas',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Thema_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Thema_UUID'], ['Themas.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Thema_UUID')
    )
    op.create_table('Beleidskeuze_Verordeningen',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Verordening_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Verordening_UUID'], ['Verordeningen.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Verordening_UUID')
    )
    op.create_table('Beleidskeuze_Werkingsgebieden',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Werkingsgebied_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Werkingsgebied_UUID'], ['Werkingsgebieden.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Werkingsgebied_UUID')
    )
    op.create_table('Beleidsmodule_Beleidskeuzes',
    sa.Column('Beleidsmodule_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Beleidsmodule_UUID'], ['Beleidsmodules.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidsmodule_UUID', 'Beleidskeuze_UUID')
    )
    op.create_table('Beleidsrelaties',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=True),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=True),
    sa.Column('Created_Date', sa.DateTime(), nullable=True),
    sa.Column('Modified_Date', sa.DateTime(), nullable=True),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Status', sa.Unicode(length=50), nullable=True),
    sa.Column('Aanvraag_Datum', sa.DateTime(), nullable=True),
    sa.Column('Datum_Akkoord', sa.DateTime(), nullable=True),
    sa.Column('Titel', sa.Unicode(length=50), server_default=sa.text("('Titel')"), nullable=False),
    sa.Column('Van_Beleidskeuze', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Naar_Beleidskeuze', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Naar_Beleidskeuze'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Van_Beleidskeuze'], ['Beleidskeuzes.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Maatregelen',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Titel', sa.Unicode(), nullable=False),
    sa.Column('Omschrijving', sa.Unicode(), nullable=True),
    sa.Column('Toelichting', sa.Unicode(), nullable=True),
    sa.Column('Toelichting_Raw', sa.Unicode(), nullable=True),
    sa.Column('Weblink', sa.Unicode(), nullable=True),
    sa.Column('Gebied', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Status', sa.Unicode(length=50), nullable=True),
    sa.Column('Gebied_Duiding', sa.Unicode(), nullable=True),
    sa.Column('Tags', sa.Unicode(), nullable=True),
    sa.Column('Aanpassing_Op', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Eigenaar_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Eigenaar_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Portefeuillehouder_1', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Portefeuillehouder_2', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Opdrachtgever', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Aanpassing_Op'], ['Maatregelen.UUID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Eigenaar_2'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Gebied'], ['Werkingsgebieden.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Opdrachtgever'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_1'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Portefeuillehouder_2'], ['Gebruikers.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Onderverdeling',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('Begin_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Eind_Geldigheid', sa.DateTime(), nullable=False),
    sa.Column('Created_Date', sa.DateTime(), nullable=False),
    sa.Column('Modified_Date', sa.DateTime(), nullable=False),
    sa.Column('Onderverdeling', sa.Unicode(), nullable=False),
    sa.Column('symbol', sa.Unicode(length=265), nullable=True),
    sa.Column('Werkingsgebied', sa.Unicode(length=256), nullable=True),
    sa.Column('UUID_Werkingsgebied', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('SHAPE', Utils.sqlalchemy.Geometry(), nullable=False),
    sa.Column('Created_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Modified_By', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['Created_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['Modified_By'], ['Gebruikers.UUID'], ),
    sa.ForeignKeyConstraint(['UUID_Werkingsgebied'], ['Werkingsgebieden.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('Beleidskeuze_Maatregelen',
    sa.Column('Beleidskeuze_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Maatregel_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidskeuze_UUID'], ['Beleidskeuzes.UUID'], ),
    sa.ForeignKeyConstraint(['Maatregel_UUID'], ['Maatregelen.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidskeuze_UUID', 'Maatregel_UUID')
    )
    op.create_table('Beleidsmodule_Maatregelen',
    sa.Column('Beleidsmodule_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Maatregel_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
    sa.ForeignKeyConstraint(['Beleidsmodule_UUID'], ['Beleidsmodules.UUID'], ),
    sa.ForeignKeyConstraint(['Maatregel_UUID'], ['Maatregelen.UUID'], ),
    sa.PrimaryKeyConstraint('Beleidsmodule_UUID', 'Maatregel_UUID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Beleidsmodule_Maatregelen')
    op.drop_table('Beleidskeuze_Maatregelen')
    op.drop_table('Onderverdeling')
    op.drop_table('Maatregelen')
    op.drop_table('Beleidsrelaties')
    op.drop_table('Beleidsmodule_Beleidskeuzes')
    op.drop_table('Beleidskeuze_Werkingsgebieden')
    op.drop_table('Beleidskeuze_Verordeningen')
    op.drop_table('Beleidskeuze_Themas')
    op.drop_table('Beleidskeuze_Beleidsregels')
    op.drop_table('Beleidskeuze_Beleidsprestaties')
    op.drop_table('Beleidskeuze_Beleidsdoelen')
    op.drop_table('Beleidskeuze_Belangen')
    op.drop_table('Beleidskeuze_Ambities')
    op.drop_table('Werkingsgebieden')
    op.drop_table('Verordeningstructuur')
    op.drop_table('Verordeningen')
    op.drop_table('Themas')
    op.drop_table('Beleidsregels')
    op.drop_table('Beleidsprestaties')
    op.drop_table('Beleidsmodules')
    op.drop_table('Beleidskeuzes')
    op.drop_table('Beleidsdoelen')
    op.drop_table('Belangen')
    op.drop_table('Ambities')
    op.drop_table('Gebruikers')
    # ### end Alembic commands ###
