"""empty message

Revision ID: f92ca6e6cc8e
Revises: abf6d713759e
Create Date: 2022-10-31 10:46:43.309302

"""
from alembic import op
import sqlalchemy as sa
import Api.Utils
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f92ca6e6cc8e'
down_revision = 'abf6d713759e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Beleidsmodule_Gebiedsprogrammas',
        sa.Column('Beleidsmodule_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column('Gebiedsprogramma_UUID', mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column('Koppeling_Omschrijving', sa.String(collation='SQL_Latin1_General_CP1_CI_AS'), nullable=True),
        sa.ForeignKeyConstraint(['Beleidsmodule_UUID'], ['Beleidsmodules.UUID'], name=op.f('FK_Beleidsmodule_Gebiedsprogrammas_Beleidsmodule_UUID')),
        sa.ForeignKeyConstraint(['Gebiedsprogramma_UUID'], ['Gebiedsprogrammas.UUID'], name=op.f('FK_Beleidsmodule_Gebiedsprogrammas_Gebiedsprogramma_UUID')),
        sa.PrimaryKeyConstraint('Beleidsmodule_UUID', 'Gebiedsprogramma_UUID', name=op.f('PK_Beleidsmodule_Gebiedsprogrammas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Beleidsmodule_Gebiedsprogrammas')
    # ### end Alembic commands ###


def dialect_supports_sequences():
    return op._proxy.migration_context.dialect.supports_sequences


def dialect_supports_geometry_index():
    return op._proxy.migration_context.dialect.name == 'mssql'


def create_seq(name):
    if dialect_supports_sequences():
       op.execute(sa.schema.CreateSequence(sa.schema.Sequence(name)))


def drop_seq(name):
    if dialect_supports_sequences():
       op.execute(sa.schema.DropSequence(sa.schema.Sequence(name)))
