searchable_config: &searchable_config
  searchable_columns_high:
    - Title
  searchable_columns_low:
    - Description
    - Effect
    - Provincial_Interest
    - Cause

sort_allowed_object_columns: &sort_allowed_object_columns
  - Object_ID
  - Title
  - Modified_Date

sort_default_title: &sort_default_title
  default:
    column: Title
    order: asc
  allowed_columns: *sort_allowed_object_columns

sort_default_modified_date: &sort_default_modified_date
  default:
    column: Modified_Date
    order: desc
  allowed_columns: *sort_allowed_object_columns

sort_default_object_id: &sort_default_object_id
  default:
    column: Object_ID
    order: asc
  allowed_columns: *sort_allowed_object_columns

api:
  routers:
    - prefix: /playground
      endpoints:
        - resolver: playground_do_dso
          resolver_data:
            path: /do-dso/{module_id}
    - prefix: /users
      endpoints:
        - resolver: list_users
          resolver_data:
            sort:
              default:
                column: Gebruikersnaam
                order: asc
              allowed_columns:
                - Gebruikersnaam
                - Rol
                - Email
        - resolver: create_user
          resolver_data:
            allowed_roles:
              - "Ambtelijk opdrachtgever"
              - "Behandelend Ambtenaar"
              - "Functioneel beheerder"
              - "Portefeuillehouder"
    - prefix: /users/search
      endpoints:
        - resolver: search_users
          resolver_data:
            sort:
              default:
                column: Gebruikersnaam
                order: asc
              allowed_columns:
                - Gebruikersnaam
                - Rol
                - Email
    - prefix: /users/{user_uuid}
      endpoints:
        - resolver: get_user
        - resolver: edit_user
          resolver_data:
            allowed_roles:
              - "Ambtelijk opdrachtgever"
              - "Behandelend Ambtenaar"
              - "Functioneel beheerder"
              - "Portefeuillehouder"
        - resolver: reset_user_password
          resolver_data:
            path: /reset-password
    - prefix: /source-werkingsgebieden
      endpoints:
        - resolver: source_list_werkingsgebieden
          resolver_data:
            sort:
              default:
                column: Title
                order: asc
              allowed_columns:
                - Title
                - ID
                - Created_Date
                - Modified_Date
    - prefix: /search/source-geo
      endpoints:
        - resolver: source_list_objects_in_werkingsgebieden
          resolver_data:
            sort: *sort_default_title
    - prefix: /search/source-geometry
      endpoints:
        - resolver: source_list_objects_by_geometry
          resolver_data:
            sort: *sort_default_title
            allowed_object_types:
              - ambitie
              - beleidsdoel
              - beleidskeuze
              - beleidsregel
              - maatregel
              - gebiedsprogramma
    - prefix: /search
      endpoints:
        - resolver: mssql_search
          resolver_data:
            <<: *searchable_config
            allowed_object_types:
              - ambitie
              - beleidsdoel
              - beleidskeuze
              - maatregel
              - beleidsregel
              - gebiedsprogramma
              - wettelijke_taak
              - nationaal_belang
              - verplicht_programma
              - visie_algemeen
              - programma_algemeen
              - werkingsgebied
    - prefix: /search/valid
      endpoints:
        - resolver: mssql_valid_search
          resolver_data:
            <<: *searchable_config
            allowed_object_types:
              - ambitie
              - beleidsdoel
              - beleidskeuze
              - maatregel
              - beleidsregel
              - gebiedsprogramma
              - wettelijke_taak
              - nationaal_belang
              - verplicht_programma
              - visie_algemeen
              - programma_algemeen
              - werkingsgebied
    - prefix: /full-graph
      endpoints:
        - resolver: full_graph
    - prefix: /object-graph
      endpoints:
        - resolver: object_graph
          resolver_data:
            graph_iterations:
              relations:
                - allowed_object_types:
                  - ambitie
                  - beleidsdoel
                  - beleidskeuze
                  - maatregel
                - allowed_object_types:
                  - ambitie
              acknowledged_relations:
                - allowed_object_types:
                  - beleidskeuze
    - prefix: /revisions
      endpoints:
        - resolver: public_list_modules
        - resolver: public_module_overview
          resolver_data:
            path: /{module_id}
    - prefix: /modules
      endpoints:
        - resolver: create_module
        - resolver: list_modules
    - prefix: /modules/{module_id}
      endpoints:
        - resolver: module_overview
        - resolver: edit_module
        - resolver: activate_module
          resolver_data:
            path: /activate
        - resolver: complete_module
          resolver_data:
            path: /complete
        - resolver: close_module
          resolver_data:
            path: /close
        - resolver: module_list_statuses
          resolver_data:
            path: /status
        - resolver: module_patch_status
          resolver_data:
            path: /status
        - resolver: module_diff
          resolver_data:
            path: /diff
            objects:
              - object_type: ambitie
                content:
                  - column: Description
                    label: Omschrijving
              - object_type: beleidsdoel
                content:
                  - column: Description
                    label: Omschrijving
                  - column: Hierarchy_Code
                    label: Hierarchy_Code
              - object_type: beleidskeuze
                content:
                  - column: Description
                    label: Wat wil de provincie bereiken?
                  - column: Cause
                    label: Aanleiding
                  - column: Provincial_Interest
                    label: Provinciaal belang
                  - column: Explanation
                    label: Toelichting
                  - column: Hierarchy_Code
                    label: Hierarchy_Code
                  - column: Gebied_UUID
                    label: Gebied_UUID
                  - column: Werkingsgebied_Code
                    label: Werkingsgebied_Code
              - object_type: maatregel
                content:
                  - column: Description
                    label: Wat wil de provincie bereiken?
                  - column: Role
                    label: Rol
                  - column: Explanation
                    label: Toelichting
                  - column: Hierarchy_Code
                    label: Hierarchy_Code
                  - column: Gebied_UUID
                    label: Gebied_UUID
                  - column: Werkingsgebied_Code
                    label: Werkingsgebied_Code
        - resolver: module_add_new_object
          resolver_data:
            path: /add-new-object
            allowed_object_types:
              - ambitie
              - beleidsdoel
              - beleidskeuze
              - maatregel
              - beleidsregel
              - gebiedsprogramma
              - visie_algemeen
              - programma_algemeen
              - werkingsgebied
        - resolver: module_add_existing_object
          resolver_data:
            path: /add-existing-object
            allowed_object_types:
              - ambitie
              - beleidsdoel
              - beleidskeuze
              - maatregel
              - beleidsregel
              - gebiedsprogramma
              - visie_algemeen
              - programma_algemeen
              - werkingsgebied
        - resolver: module_get_object_context
          resolver_data:
            path: /object-context/{object_type}/{lineage_id}
        - resolver: module_edit_object_context
          resolver_data:
            path: /object-context/{object_type}/{lineage_id}
        - resolver: module_remove_object
          resolver_data:
            path: /remove/{object_type}/{lineage_id}
        - resolver: module_snapshot
          resolver_data:
            path: /snapshot/{status_id}
    - prefix: /modules/objects/latest
      endpoints:
        - resolver: list_module_objects
          resolver_data:
            sort: *sort_default_modified_date
    - prefix: /objects/valid
      endpoints:
        - resolver: object_counts
          resolver_data:
            path: /count
        - resolver: list_all_latest_objects
          resolver_data:
            sort: *sort_default_object_id
    - prefix: /publications/bills
      endpoints:
        - resolver: list_publication_bills
          resolver_data:
            sort: *sort_default_modified_date
        - resolver: create_publication_bill
    - prefix: /publications/packages
      endpoints:
        - resolver: create_publication_package
        - resolver: list_publication_package
          resolver_data:
            sort: *sort_default_modified_date

columns:
  # Titel
  title:
    name: Title
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Omschrijving
  description:
    name: Description
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Area_UUID used to store reference to the shape
  area_uuid:
    name: Area_UUID
    type: area_uuid
    type_data:
      relation_field: Area
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
  # Beschrijf de uitwerking van het object
  effect:
    name: Effect
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Rol
  role:
    name: Role
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Provinciaal Belang
  provincial_interest:
    name: Provincial_Interest
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Aanleiding
  cause:
    name: Cause
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Besluitnummer
  decision_number:
    name: Decision_Number
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Toelichting
  explanation:
    name: Explanation
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Weblink
  weblink:
    name: Weblink
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # IDMS Link
  idms_link:
    name: IDMS_Link
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Gebied UUID
  gebied_uuid:
    name: Gebied_UUID
    type: werkingsgebied_uuid
    type_data:
      relation_field: Gebied
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
  # Gebied Duiding
  gebied_duiding:
    name: Gebied_Duiding
    type: str
    serializers: []
    deserializers: ["str"]
    nullable: true
  # Primaire koppeling
  hierarchy_code:
    name: Hierarchy_Code
    type: object_code
    type_data:
      relation_field: Hierarchy_Statics
    serializers: ["optional_str"]
    deserializers: ["optional_str"]
    nullable: true
  werkingsgebied_code:
    name: Werkingsgebied_Code
    type: object_code
    type_data:
      relation_field: Werkingsgebied_Statics
    serializers: ["optional_str"]
    deserializers: ["optional_str"]
    nullable: true
  # Image
  image:
    name: Image
    type: str
    serializers: []
    deserializers: []
    nullable: true
  # Eigenaar 1
  owner_1_uuid:
    name: Owner_1_UUID
    type: user_uuid
    type_data:
      relation_field: Owner_1
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
    static: true
  # Eigenaar 2
  owner_2_uuid:
    name: Owner_2_UUID
    type: user_uuid
    type_data:
      relation_field: Owner_2
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
    static: true
  # Portefeuillehouder 1
  portfolio_holder_1_uuid:
    name: Portfolio_Holder_1_UUID
    type: user_uuid
    type_data:
      relation_field: Portfolio_Holder_1
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
    static: true
  # Portefeuillehouder 2
  portfolio_holder_2_uuid:
    name: Portfolio_Holder_2_UUID
    type: user_uuid
    type_data:
      relation_field: Portfolio_Holder_2
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
    static: true
  # Opdrachtgever
  client_1_uuid:
    name: Client_1_UUID
    type: user_uuid
    type_data:
      relation_field: Client_1
    serializers: ["optional_str"]
    deserializers: ["optional_uuid"]
    nullable: true
    static: true

users_permissions:
  "Ambtelijk opdrachtgever": []
  "Behandelend Ambtenaar":
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
  "Beheerder":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static
  "Portefeuillehouder": []
  "Functioneel beheerder":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static
  "Technisch beheerder":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static
  "Superuser":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static
  "Test runner":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static
  "Tester":
    - atemporal_can_create_object
    - atemporal_can_edit_object
    - atemporal_can_delete_object
    - can_create_module
    - can_close_module
    - can_edit_module
    - can_activate_module
    - can_patch_module_status
    - can_add_new_object_to_module
    - can_add_existing_object_to_module
    - can_edit_module_object_context
    - can_remove_object_from_module
    - can_patch_object_in_module
    - can_create_user
    - can_edit_user
    - can_reset_user_password
    - can_patch_object_static

modules_pdf_export:
  # prefixed by /config/
  template_path: /extensions/module_pdf_export/templates
  templates:
    ambitie: ambitie.j2
    beleidsdoel: beleidsdoel.j2
    beleidskeuze: beleidskeuze.j2
    maatregel: maatregel.j2
  # prefixed by /output/
  destination_path: /extensions/module_pdf_export

modules_xml_export:
  destination_path: /extensions/module_xml_export

mssql_search:
  - table_name: objects
    <<: *searchable_config
  - table_name: module_objects
    <<: *searchable_config
