from .attachments.delete_attachment import DeletePublicationVersionAttachmentEndpointResolver
from .attachments.upload_attachment import UploadPublicationVersionAttachmentEndpointResolver
from .create_pdf import CreatePublicationVersionPdfEndpointResolver
from .create_version import CreatePublicationVersionEndpointResolver
from .detail_version import DetailPublicationVersionEndpointResolver
from .edit_version import EditPublicationVersionEndpointResolver
from .list_versions import ListPublicationVersionsEndpointResolver
