from .create_version import CreatePublicationVersionEndpointResolver
from .detail_version import DetailPublicationVersionEndpointResolver
from .edit_version import EditPublicationVersionEndpointResolver
from .list_versions import ListPublicationVersionsEndpointResolver
from .upload_attachment import UploadPublicationVersionAttachmentEndpointResolver
