from .close_act import ClosePublicationActEndpointResolver
from .create_act import CreateActEndpointResolver
from .detail_act import DetailPublicationActEndpointResolver
from .edit_act import EditPublicationActEndpointResolver
from .list_acts import ListPublicationActsEndpointResolver
