from .models import Column


base_columns = [
    Column(
        id="object_id",
        name="Object_ID",
        type="int",
        serializers=[],
        deserializers=[],
    ),
    Column(
        id="uuid",
        name="UUID",
        type="str",
        serializers=[
            "str",
        ],
        deserializers=[
            "uuid",
        ],
    ),
    Column(
        id="object_type",
        name="Object_Type",
        type="str_25",
    ),
    Column(
        id="code",
        name="Code",
        type="str_35",
    ),
    Column(
        id="created_date",
        name="Created_Date",
        type="datetime",
    ),
    Column(
        id="modified_date",
        name="Modified_Date",
        type="datetime",
    ),
    Column(
        id="adjust_on",
        name="Adjust_On",
        type="object_uuid",
        nullable=True,
        serializers=[
            "optional_str",
        ],
        deserializers=[
            "optional_uuid",
        ],
    ),
    Column(
        id="created_by_uuid",
        name="Created_By_UUID",
        type="user_uuid",
        type_data={
            "relation_field": "Created_By",
        },
        serializers=[
            "str",
        ],
        deserializers=[
            "uuid",
        ],
    ),
    Column(
        id="modified_by_uuid",
        name="Modified_By_UUID",
        type="user_uuid",
        type_data={
            "relation_field": "Modified_By",
        },
        serializers=[
            "str",
        ],
        deserializers=[
            "uuid",
        ],
    ),
    Column(
        id="start_validity",
        name="Start_Validity",
        nullable=True,
        type="datetime",
    ),
    Column(
        id="end_validity",
        name="End_Validity",
        nullable=True,
        type="datetime",
    ),
]
