from .create_template_endpoint import post_create_template_endpoint
from .detail_template_endpoint import get_detail_template_endpoint
from .edit_template_endpoint import post_edit_template_endpoint
from .list_templates_endpoint import get_list_templates_endpoint
