from .create_template import CreatePublicationTemplateEndpointResolver
from .detail_template import DetailPublicationTemplateEndpointResolver
from .edit_template import EditPublicationTemplateEndpointResolver
from .list_templates import ListPublicationTemplatesEndpointResolver
